#!/usr/bin/env Rscript
#=======================================================================================
# Generic SIR Step 2 - Aggregate QC and Index Script
#
# This script processes ONE individual Monte Carlo simulation using the new
# specification-driven generic framework. Each call processes a single simulation ID.
#
# Usage: Rscript sir_step2_aggregate_qc.R <config_path>  
#
# Arguments:
#   config_path  - Path to YAML configuration file 
#
# Author: Generated by Claude Code for DayCent Calibration Framework
# Date: March 2026
#=======================================================================================

# Parse command line arguments
args <- commandArgs(trailingOnly = TRUE)
if (length(args) > 0) {
    config_path <- args[1] # Path to YAML config file 
} else {
    # config_path <- "workflows/configs/crop_yield_corn_all.yaml"
}

# Load YAML to get custom library path (minimal setup)
if (!require(yaml, quietly = TRUE)) {
    stop("yaml package not available. Please run step0_r_setup.R first.")
}
config <- yaml::read_yaml(config_path)
  
# Set custom library path (packages should already be installed by step0_r_setup.R)
if (!is.null(config$r_config$rlibpaths)) {
    .libPaths(new = c(config$r_config$rlibpaths, .libPaths()))
}

# Load required packages (assuming they are already installed)
suppressPackageStartupMessages({
  library(bayesiancalibr)
})


# Validate inputs
if (!file.exists(config_path)) {
  cat("ERROR: Configuration file not found:", config_path, "\n")
  quit(status = 1)
}
 

# Load configuration
cat("=== Individual GSA Step 2 Simulation ===\n")
cat("Loading configuration from:", config_path, "\n")

config <- tryCatch({
  read_yaml_config(config_path)
}, error = function(e) {
  cat("ERROR: Failed to load configuration:", e$message, "\n")
  quit(status = 1)
})

# Resolve paths
config <- resolve_config_paths(config)

# Set up index
db_result_cfg <- config$file_source$database$database_result
if (is.null(db_result_cfg)) {
  cat("Skipping result tables: database_result not in config\n")
} else {
  weighted_table =  config$file_source$database$database_result$tables$sir_results_weighted
  host <- db_result_cfg$host
  database <- db_result_cfg$database
  cred_file <- db_result_cfg$cred_file %||% "~/.dblogin"
  
  cred <- readLines(path.expand(cred_file), warn = FALSE)
  if (length(cred) < 2) stop("Credential file must contain at least 2 lines (username, password)")
  username <- trimws(cred[1])
  password <- trimws(cred[2])
  
  has_mariadb <- requireNamespace("RMariaDB", quietly = TRUE)
  has_mysql <- requireNamespace("RMySQL", quietly = TRUE)
  if (!requireNamespace("DBI", quietly = TRUE)) stop("Package 'DBI' is required")
  if (!has_mariadb && !has_mysql) stop("Package 'RMariaDB' or 'RMySQL' is required")
  
  if (has_mariadb) {
    dbConn_postproc <- DBI::dbConnect(
      RMariaDB::MariaDB(),
      host = host, dbname = database,
      username = username, password = password
    )
  } else {
    dbConn_postproc <- DBI::dbConnect(
      RMySQL::MySQL(),
      host = host, dbname = database,
      username = username, password = password
    )
  }
  on.exit(DBI::dbDisconnect(dbConn_postproc), add = TRUE)
  cat("Connected to database\n") 

  cat("Weighted table:", weighted_table, "\n")

  add_index_if_missing <- function(conn, table_name, index_name, column_name) {
    existing_index <- DBI::dbGetQuery(
      conn,
      paste0("SHOW INDEX FROM ", table_name, " WHERE Key_name = '", index_name, "'")
    )

    if (nrow(existing_index) > 0) {
      cat("Index already exists, skipping:", index_name, "\n")
      return(invisible(FALSE))
    }

    tryCatch({
      DBI::dbExecute(
        conn,
        paste0("ALTER TABLE ", table_name, " ADD INDEX ", index_name, " (", column_name, ");")
      )
      cat("Index created:", index_name, "\n")
      invisible(TRUE)
    }, error = function(e) {
      cat("Index creation failed, continuing:", index_name, "-", conditionMessage(e), "\n")
      invisible(FALSE)
    })
  }
 
  add_index_if_missing(dbConn_postproc, weighted_table, "idx_job", "job_group")
  add_index_if_missing(dbConn_postproc, weighted_table, "idx_simulate", "simulation_id") 
  
  DBI::dbDisconnect(dbConn_postproc)
  cat("Disconnected from database\n") 
}


q()