#!/usr/bin/env Rscript
#=======================================================================================
# SIR Step 2 - Individual Simulation Wrapper Script
#
# This script processes ONE individual SIR Monte Carlo simulation using the new
# generic framework. Each call processes a single simulation ID.
#
# Usage: Rscript sir_step2_simulate.R <config_path> <sim_id> [daycent_exe] [scratch_dir]
#
# Arguments:
#   config_path  - Path to YAML configuration file
#   sim_id       - Individual simulation ID (1 to nsim)
#   daycent_exe  - Optional: Path to DayCent executable (defaults to config)
#   scratch_dir  - Optional: Scratch directory path (defaults to config scratch_dir or /tmp/daycent_<pid>)
#
# Author: Generated by Claude Code for DayCent Calibration Framework
# Date: July 2025
#=======================================================================================

# Parse command line arguments
args <- commandArgs(trailingOnly = TRUE)
if (length(args) < 2) {
    stop("Usage: Rscript sir_step2_simulate.R <config_path> <sim_id> [daycent_exe] [scratch_dir]")
}

config_path <- args[1] # Path to YAML config file
sim_id <- as.numeric(args[2]) # Individual simulation ID

# Load YAML to get custom library path (minimal setup)
if (!require(yaml, quietly = TRUE)) {
    stop("yaml package not available. Please run step0_r_setup.R first.")
}
config <- yaml::read_yaml(config_path)

# Set custom library path (packages should already be installed by step0_r_setup.R)
if (!is.null(config$r_config$rlibpaths)) {
    .libPaths(new = c(config$r_config$rlibpaths, .libPaths()))
}

# Load required packages (assuming they are already installed)
suppressPackageStartupMessages({
  library(bayesiancalibr)
})

# Continue with argument parsing
cat("Running SIR Step 2 with arguments:\n")
cat("Config file:", config_path, "\n")
cat("Simulation ID:", sim_id, "\n")

# Parse optional --partition-id argument for scaling mode
partition_id_override <- NULL
if ("--partition-id" %in% args) {
  partition_id_idx <- which(args == "--partition-id")
  if (length(args) > partition_id_idx) {
    partition_id_override <- as.integer(args[partition_id_idx + 1])
    cat("Partition ID override:", partition_id_override, "(Scaling mode partition filtering)\n")
  }
}

# Optional arguments
daycent_exe <- if(length(args) >= 3) args[3] else NULL
scratch_dir <- if(length(args) >= 4) args[4] else NULL

# Validate inputs
if (!file.exists(config_path)) {
  cat("ERROR: Configuration file not found:", config_path, "\n")
  quit(status = 1)
}

if (is.na(sim_id) || sim_id < 1) {
  cat("ERROR: sim_id must be a positive integer, got:", sim_id, "\n")
  quit(status = 1)
}

# Load configuration
cat("=== Individual SIR Step 2 Simulation ===\n")
cat("Loading configuration from:", config_path, "\n")

config <- tryCatch({
  read_yaml_config(config_path)
}, error = function(e) {
  cat("ERROR: Failed to load configuration:", e$message, "\n")
  quit(status = 1)
})

# Resolve paths
config <- resolve_config_paths(config)

# Set up DayCent executable path
if (is.null(daycent_exe)) {
  if ("daycent" %in% names(config) && "executable" %in% names(config$daycent)) {
    daycent_exe <- file.path(config$paths$lairice_root, config$daycent$executable)
  } else {
    cat("ERROR: DayCent executable not specified in config or command line\n")
    quit(status = 1)
  }
}

# Set up scratch directory
if (is.null(scratch_dir)) {
  # Use scratch directory from config if available, otherwise fallback to config default
  if ("cluster" %in% names(config) && "scratch_dir" %in% names(config$cluster)) {
    scratch_dir <- file.path(config$cluster$scratch_dir, paste0("daycent_sir_", Sys.getpid()))
  } else {
    scratch_dir <- paste0("/tmp/daycent_sir_", Sys.getpid())
  }
}

# Display run information
cat("Project:", config$project$name, "\n")
cat("Simulation ID:", sim_id, "\n")
cat("DayCent executable:", daycent_exe, "\n")
cat("Scratch directory:", scratch_dir, "\n")
cat("Configuration validated successfully\n")

# Record start time
start_time <- Sys.time()
cat("Starting simulation at:", format(start_time), "\n")

# Calculate expected database operations based on sites to be processed
# Each site typically requires ~5-6 database operations (schedule files + site files + weather lookups)
# We'll use a conservative estimate of 5 operations per site
run_file_path <- file.path(config$paths$lairice_root,
                          config$paths$output_base,
                          config$project$date_stamp,
                          "SIR", "RunFile.rds")
expected_operations <- 1  # Default fallback

if (file.exists(run_file_path)) {
  tryCatch({
    run_file <- readRDS(run_file_path)
    n_sites <- nrow(run_file)
    expected_operations <- n_sites * 5  # Estimate 5 DB operations per site
    cat("Estimated database operations:", expected_operations, "(", n_sites, "sites × 5 ops/site)\n")
  }, error = function(e) {
    cat("Could not load RunFile, using default expected_operations =", expected_operations, "\n")
  })
} else {
  cat("RunFile not found, using default expected_operations =", expected_operations, "\n")
}

# Determine if connection pooling should be used
pooling_strategy <- determine_pooling_strategy(config, expected_operations = expected_operations, log_function = cat)
shared_con <- NULL

if (pooling_strategy$use_pooling) {
  cat("Setting up shared database connection...\n")
  shared_con <- get_shared_connection(config, log_function = cat)
  if (is.null(shared_con)) {
    cat("Warning: Failed to create shared connection, falling back to individual connections\n")
  }
}

# Run individual simulation using SIR framework
cat("\n=== Running Individual SIR Step 2 Simulation ===\n")
result <- tryCatch({
  # Call the SIR-specific individual simulation function
  sir_step2_simulate_individual(
    config = config,
    sim_id = sim_id,
    daycent_exe = daycent_exe,
    scratch_dir = scratch_dir,
    clean_scratch = config$cluster$clean_scratch,
    start_id = 0,
    partition_id_override = partition_id_override,  # Pass for scaling mode
    shared_connection = shared_con,
    verbose = TRUE
  )
}, error = function(e) {
  cat("ERROR: Individual SIR Step 2 simulation failed:", e$message, "\n")
  # Clean up shared connection on error
  if (!is.null(shared_con)) {
    close_shared_connection(config, log_function = cat)
  }
  quit(status = 1)
})

# Record end time and duration
end_time <- Sys.time()
duration <- end_time - start_time
cat("\n=== Simulation Complete ===\n")
cat("End time:", format(end_time), "\n")
cat("Duration:", format(duration), "\n")

# Display results summary
if (result$status == 0) {
  cat("Status: SUCCESS\n")
  cat("Simulation ID processed:", result$sim_id, "\n")
  
  if (!is.null(result$daily_results)) {
    cat("Daily results shape:", nrow(result$daily_results), "rows x", ncol(result$daily_results), "columns\n")
  }
  
  if (!is.null(result$aggregated_results)) {
    cat("Aggregated results shape:", nrow(result$aggregated_results), "rows x", ncol(result$aggregated_results), "columns\n")
  }
  
  if (!is.null(result$runtime_info)) {
    cat("Runtime information: 1 simulation record\n")
    cat("  Sites processed:", result$runtime_info$num_trts, "\n")
    cat("  Simulation years:", result$runtime_info$sim_years, "\n")
    cat("  Execution time:", result$runtime_info$Time_sec, "seconds\n")
  }
  
  if (!is.null(result$output_files) && length(result$output_files) > 0) {
    cat("Output files created:\n")
    for (i in seq_along(result$output_files)) {
      cat("  ", names(result$output_files)[i], ":", result$output_files[[i]], "\n")
    }
  }
  
  cat("\nIndividual SIR Step 2 simulation completed successfully!\n")

  # Clean up shared connection if created
  if (!is.null(shared_con)) {
    close_shared_connection(config, log_function = cat)
  }

  quit(status = 0)

} else {
  cat("Status: FAILED\n")
  cat("Individual SIR Step 2 simulation failed with status code:", result$status, "\n")
  if (!is.null(result$runtime_info)) {
    cat("Error message:", result$runtime_info$message, "\n")
  }

  # Clean up shared connection if created (even on failure)
  if (!is.null(shared_con)) {
    close_shared_connection(config, log_function = cat)
  }

  quit(status = 1)
}