#!/usr/bin/env Rscript
#=======================================================================================
# SIR Step 2 Aggregate - Weighted Mean Aggregation
#
# This script performs weighted mean aggregation on annual results from SIR Step 2
# simulations run in scaling mode. It loads all annual results and applies weighted
# aggregation across NRI points based on aggregation_level and aggregation_weight.
#
# Usage: Rscript sir_step2_aggregate.R <config_path> [sample_ids]
#
# Arguments:
#   config_path  - Path to YAML configuration file
#   sample_ids   - Optional: Comma-separated list of sample IDs (e.g., "1,2,3,10-20")
#                  If not specified, processes all samples found
#
# Author: Generated by Claude Code for DayCent Calibration Framework
# Date: October 2025
#=======================================================================================

# Parse command line arguments
args <- commandArgs(trailingOnly = TRUE)
if (length(args) > 0) {
  config_path <- args[1] # Path to YAML config file
} else {
  print("No config file found")
  config_path <- "workflows/configs/crop_yield_wheat_W3.yaml"
}

# Load YAML to get custom library path (minimal setup)
if (!require(yaml, quietly = TRUE)) {
  stop("yaml package not available. Please run step0_r_setup.R first.")
}
config <- yaml::read_yaml(config_path)

# Set custom library path
if (!is.null(config$r_config$rlibpaths)) {
  .libPaths(new = c(config$r_config$rlibpaths, .libPaths()))
}

# Load required packages
suppressPackageStartupMessages({
  library(bayesiancalibr)
})

# Continue with argument parsing
if (length(args) > 0) {
  # Parse sample IDs if provided
  sample_ids <- NULL
  if (length(args) >= 2) {
    sample_ids_str <- args[2]
    # Parse comma-separated list with range support (e.g., "1,2,3,10-20")
    parts <- strsplit(sample_ids_str, ",")[[1]]
    sample_ids <- c()
    for (part in parts) {
      if (grepl("-", part)) {
        # Range (e.g., "10-20")
        range_vals <- as.integer(strsplit(part, "-")[[1]])
        sample_ids <- c(sample_ids, range_vals[1]:range_vals[2])
      } else {
        # Single value
        sample_ids <- c(sample_ids, as.integer(part))
      }
    }
  }
  
  cat("Running SIR Step 2 Aggregate with command line arguments:\n")
  flush.console()
  cat("Config file:", config_path, "\n")
  if (!is.null(sample_ids)) {
    cat("Sample IDs:", length(sample_ids), "samples specified\n")
  } else {
    cat("Sample IDs: All samples (auto-detect)\n")
  }
  cat("\n")
  flush.console()
} else {
  # Interactive usage with defaults
  print("No config file found")
  sample_ids <- 1 # Process all samples
  
  cat("Running SIR Step 2 Aggregate with default configuration:\n")
  cat("Config file:", config_path, "\n")
  cat("Sample IDs: All samples (auto-detect)\n\n")
}

# Validate inputs
if (!file.exists(config_path)) {
  cat("ERROR: Configuration file not found:", config_path, "\n")
  quit(status = 1)
}

# Load configuration
cat("=== SIR Step 2 Aggregate ===\n")
cat("Loading configuration from:", config_path, "\n")

config <- tryCatch({
  read_yaml_config(config_path)
}, error = function(e) {
  cat("ERROR: Failed to load configuration:", e$message, "\n")
  quit(status = 1)
})

# Resolve paths
config <- resolve_config_paths(config)

# Display run information
cat("Project:", config$project$name, "\n")
cat("Configuration validated successfully\n\n")

# Record start time
start_time <- Sys.time()
cat("Starting aggregation at:", format(start_time), "\n\n")
flush.console()

# Run aggregation
cat("=== Running Weighted Mean Aggregation ===\n")
result <- tryCatch({
  sir_step2_aggregate(
    config = config,
    sample_ids = sample_ids,
    verbose = TRUE
  )
}, error = function(e) {
  cat("ERROR: SIR Step 2 aggregation failed:", e$message, "\n")
  cat("Traceback:\n")
  print(traceback())
  quit(status = 1)
})

# Record end time and duration
end_time <- Sys.time()
duration <- end_time - start_time
cat("\n=== Aggregation Complete ===\n")
cat("End time:", format(end_time), "\n")
cat("Duration:", format(duration), "\n")

# Display results summary
if (result$status == 0) {
  cat("\nStatus: SUCCESS\n")
  cat("Message:", result$message, "\n")
  cat("Samples processed:", result$samples_processed, "\n")
  cat("Samples failed:", result$samples_failed, "\n")
  cat("Total samples:", result$total_samples, "\n")
  cat("Elapsed time:", round(result$elapsed_time_sec, 2), "seconds\n")

  cat("\nSIR Step 2 Aggregate completed successfully!\n")
  quit(status = 0)
} else {
  cat("\nStatus: PARTIAL SUCCESS or FAILURE\n")
  cat("Message:", result$message, "\n")
  cat("Samples processed:", result$samples_processed, "\n")
  cat("Samples failed:", result$samples_failed, "\n")
  cat("Total samples:", result$total_samples, "\n")

  cat("\nSIR Step 2 Aggregate completed with errors\n")
  quit(status = 1)
}
