#!/usr/bin/env bash
#=======================================================================================
# SIR Step 2 Aggregate SLURM Submission Script - Weighted Mean Aggregation
#
# Weighted mean aggregation for SIR Step 2 (scaling mode).
# One sample per array task via SLURM_ARRAY_TASK_ID.
#
# USAGE:
#   sbatch --array=1-N sir_step2_aggregate_rubel.sh <config.yaml>
#
# Arguments:
#   config.yaml  - Required: basename, name.yaml, or path under workflows/configs/
#
# Examples:
#   sbatch --array=1-100000 workflows/scripts/ShellScripts/SIR/sir_step2_aggregate_rubel.sh \
#       crop_yield_corn_all.yaml
#   sbatch --array=1-250000 workflows/scripts/ShellScripts/SIR/sir_step2_aggregate_rubel.sh \
#       crop_yield_corn_m2.yaml 
#
# R: sir_step2_aggregate.R <config_path> [sample_ids]
#
# Author: Generated by Claude Code for DayCent Calibration Framework
# Date: August 2026
#=======================================================================================

#SBATCH --job-name=sirS2_agg
#SBATCH --ntasks=1
#SBATCH --mem-per-cpu=1GB
#SBATCH --exclude=rubel-031,rubel-041
#SBATCH --partition=rubel
##SBATCH --time=02:00:00

##SBATCH --output=/data/rubelscratch/rubelogle/daycent_calibration/LogFiles/SIR_Step2_Aggregate_stdout_%A-%a.log
##SBATCH --error=/data/rubelscratch/rubelogle/daycent_calibration/LogFiles/SIR_Step2_Aggregate_stderr_%A-%a.log
#SBATCH --output=/dev/null
#SBATCH --error=/dev/null

##SBATCH --mail-user=luqi.jiaoemanuele@colostate.edu
##SBATCH --mail-type=BEGIN,END,FAIL

# =======================================================================================
# Project root (absolute for SLURM spool compatibility)
# =======================================================================================
PROJECT_ROOT="/data/rubelscratch/rubelogle/daycent_calibration"
CONFIGS_DIR="$PROJECT_ROOT/workflows/configs"

# =======================================================================================
# Config (required $1) — no GSA method for SIR
# =======================================================================================
if [[ -z "${1:-}" ]]; then
  echo "ERROR: YAML config argument is required."
  echo ""
  echo "Usage:"
  echo "  sbatch --array=1-N $0 <config.yaml>"
  echo ""
  echo "Examples:"
  echo "  sbatch --array=1-100000 $0 crop_yield_corn_all.yaml"
  echo "  sbatch --array=1-250000 $0 crop_yield_corn_m2.yaml"
  echo "  sbatch --array=1-1024   $0 soil_organic_carbon.yaml"
  exit 1
fi
CONFIG_ARG="$1"

resolve_config_path() {
  local arg="$1"
  local path=""

  if [[ "$arg" == /* ]] && [[ -f "$arg" ]]; then
    path="$arg"
  elif [[ -f "$arg" ]]; then
    path="$(cd "$(dirname "$arg")" && pwd)/$(basename "$arg")"
  elif [[ -f "$CONFIGS_DIR/$arg" ]]; then
    path="$CONFIGS_DIR/$arg"
  elif [[ "$arg" != *.yaml ]] && [[ -f "$CONFIGS_DIR/${arg}.yaml" ]]; then
    path="$CONFIGS_DIR/${arg}.yaml"
  elif [[ -f "$PROJECT_ROOT/$arg" ]]; then
    path="$PROJECT_ROOT/$arg"
  elif [[ -f "$PROJECT_ROOT/workflows/configs/$arg" ]]; then
    path="$PROJECT_ROOT/workflows/configs/$arg"
  else
    path=""
  fi
  echo "$path"
}

CONFIG_PATH="$(resolve_config_path "$CONFIG_ARG")"

if [[ -z "$CONFIG_PATH" || ! -f "$CONFIG_PATH" ]]; then
  echo "ERROR: Config file not found for argument: '$CONFIG_ARG'"
  echo "Looked under: as given, $CONFIGS_DIR/<name>[.yaml], $PROJECT_ROOT/..."
  echo "Usage: sbatch --array=1-N $0 <config.yaml>"
  exit 1
fi

SAMPLE_ID="${SLURM_ARRAY_TASK_ID:-}"
if [[ -z "$SAMPLE_ID" ]]; then
  echo "ERROR: SLURM_ARRAY_TASK_ID is not set."
  echo "Submit with an array, e.g.:"
  echo "  sbatch --array=1-100000 $0 $CONFIG_ARG"
  exit 1
fi

WRAPPER_SCRIPT="$PROJECT_ROOT/workflows/scripts/RScripts/SIR/sir_step2_aggregate.R"
if [[ ! -f "$WRAPPER_SCRIPT" ]]; then
  WRAPPER_SCRIPT="$PROJECT_ROOT/workflows/scripts/crop_yield_all/SIR/sir_step2_aggregate.R"
fi

echo "=== SIR Step 2 Aggregate Started ==="
date
echo "Job ID: $SLURM_JOB_ID"
echo "Array Task ID (sample_id): $SAMPLE_ID"
echo "Node: $SLURM_JOB_NODELIST"
echo "Config argument: $CONFIG_ARG"
echo "Configuration: $CONFIG_PATH"
echo "Root directory: $PROJECT_ROOT"
echo "Wrapper script: $WRAPPER_SCRIPT"
echo "Working directory: $(pwd)"

if [[ ! -f "$WRAPPER_SCRIPT" ]]; then
  echo "ERROR: R script not found: $WRAPPER_SCRIPT"
  exit 1
fi

echo ""
echo "=== Starting SIR Step 2 Aggregate ==="
echo "Command: Rscript --vanilla $WRAPPER_SCRIPT $CONFIG_PATH $SAMPLE_ID"
echo ""

Rscript --vanilla "$WRAPPER_SCRIPT" "$CONFIG_PATH" "$SAMPLE_ID"
EXIT_STATUS=$?

echo ""
echo "=== SIR Step 2 Aggregate Job Completed ==="
date
echo "Exit Status: $EXIT_STATUS"

exit $EXIT_STATUS
