#!/usr/bin/env bash
#=======================================================================================
# GSA Step 2 Aggregate SLURM Submission Script - Weighted Mean Aggregation
#
# Performs weighted mean aggregation on annual results from GSA Step 2
# (typically one sample per array task via SLURM_ARRAY_TASK_ID).
#
# USAGE:
#   sbatch --array=1-66560 gsa_step2_aggregate_rubel.sh <config.yaml> [gsa_method]
#
# Arguments:
#   config.yaml  - Required: config basename, name.yaml, or path under workflows/configs/
#   gsa_method   - Optional: GSA method name (default: soboljansen)
#
# Examples:
#   sbatch --array=1-66560 workflows/scripts/ShellScripts/GSA/gsa_step2_aggregate_rubel.sh \
#       crop_yield_corn_all.yaml
#   sbatch --array=1-66560 workflows/scripts/ShellScripts/GSA/gsa_step2_aggregate_rubel.sh \
#       crop_yield_corn_C6.yaml soboljansen
#   sbatch --array=1-1024 workflows/scripts/ShellScripts/GSA/gsa_step2_aggregate_rubel.sh \
#       soil_organic_carbon.yaml sobol
#
# Author: Generated by Claude Code for DayCent Calibration Framework
# Date: August 2026
#=======================================================================================

#SBATCH --job-name=gsaS2_agg        # Name for the job
#SBATCH --ntasks=1
#SBATCH --mem-per-cpu=1GB
#SBATCH --exclude=rubel-030
#SBATCH --partition=rubel
##SBATCH --time=02:00:00

# Log files (relative to submission directory)
##SBATCH --output=/data/rubelscratch/rubelogle/daycent_calibration/LogFiles/GSA_Step2_Aggregate_stdout_%A-%a.log
##SBATCH --error=/data/rubelscratch/rubelogle/daycent_calibration/LogFiles/GSA_Step2_Aggregate_stderr_%A-%a.log
#SBATCH --output=/dev/null
#SBATCH --error=/dev/null

# Email notifications
##SBATCH --mail-user=luqi.jiaoemanuele@colostate.edu
##SBATCH --mail-type=BEGIN,END,FAIL

# =======================================================================================
# Project root (absolute for SLURM spool compatibility)
# =======================================================================================
PROJECT_ROOT="/data/rubelscratch/rubelogle/daycent_calibration"
CONFIGS_DIR="$PROJECT_ROOT/workflows/configs"

# =======================================================================================
# Config (required $1); GSA method (optional $2, default soboljansen)
# =======================================================================================
if [[ -z "${1:-}" ]]; then
  echo "ERROR: YAML config argument is required."
  echo ""
  echo "Usage:"
  echo "  sbatch --array=1-N $0 <config.yaml> [gsa_method]"
  echo ""
  echo "Examples:"
  echo "  sbatch --array=1-66560 $0 crop_yield_corn_all.yaml"
  echo "  sbatch --array=1-66560 $0 crop_yield_corn_C6.yaml soboljansen"
  echo "  sbatch --array=1-66560 $0 crop_yield_corn_all.yaml sobol"
  exit 1
fi
CONFIG_ARG="$1"
GSA_METHOD="${2:-soboljansen}"

resolve_config_path() {
  local arg="$1"
  local path=""

  if [[ "$arg" == /* ]] && [[ -f "$arg" ]]; then
    path="$arg"
  elif [[ -f "$arg" ]]; then
    path="$(cd "$(dirname "$arg")" && pwd)/$(basename "$arg")"
  elif [[ -f "$CONFIGS_DIR/$arg" ]]; then
    path="$CONFIGS_DIR/$arg"
  elif [[ "$arg" != *.yaml ]] && [[ -f "$CONFIGS_DIR/${arg}.yaml" ]]; then
    path="$CONFIGS_DIR/${arg}.yaml"
  elif [[ -f "$PROJECT_ROOT/$arg" ]]; then
    path="$PROJECT_ROOT/$arg"
  elif [[ -f "$PROJECT_ROOT/workflows/configs/$arg" ]]; then
    path="$PROJECT_ROOT/workflows/configs/$arg"
  else
    path=""
  fi
  echo "$path"
}

CONFIG_PATH="$(resolve_config_path "$CONFIG_ARG")"

if [[ -z "$CONFIG_PATH" || ! -f "$CONFIG_PATH" ]]; then
  echo "ERROR: Config file not found for argument: '$CONFIG_ARG'"
  echo "Looked under: as given, $CONFIGS_DIR/<name>[.yaml], $PROJECT_ROOT/..."
  echo "Usage: sbatch --array=1-N $0 <config.yaml> [gsa_method]"
  exit 1
fi

# Sample ID from SLURM array (one sample per array task)
SAMPLE_ID="${SLURM_ARRAY_TASK_ID:-}"
if [[ -z "$SAMPLE_ID" ]]; then
  echo "ERROR: SLURM_ARRAY_TASK_ID is not set."
  echo "Submit with an array, e.g.:"
  echo "  sbatch --array=1-66560 $0 $CONFIG_ARG [$GSA_METHOD]"
  exit 1
fi

# Wrapper R script (prefer shared RScripts tree)
WRAPPER_SCRIPT="$PROJECT_ROOT/workflows/scripts/RScripts/GSA/gsa_step2_aggregate.R"
if [[ ! -f "$WRAPPER_SCRIPT" ]]; then
  WRAPPER_SCRIPT="$PROJECT_ROOT/workflows/scripts/crop_yield_all/GSA/gsa_step2_aggregate.R"
fi

echo "=== GSA Step 2 Aggregate Started ==="
date
echo "Job ID: $SLURM_JOB_ID"
echo "Array Task ID (sample_id): $SAMPLE_ID"
echo "Node: $SLURM_JOB_NODELIST"
echo "Config argument: $CONFIG_ARG"
echo "Configuration: $CONFIG_PATH"
echo "GSA Method: $GSA_METHOD (default soboljansen if not provided)"
echo "Root directory: $PROJECT_ROOT"
echo "Wrapper script: $WRAPPER_SCRIPT"
echo "Working directory: $(pwd)"

if [[ ! -f "$WRAPPER_SCRIPT" ]]; then
  echo "ERROR: R script not found: $WRAPPER_SCRIPT"
  exit 1
fi

echo ""
echo "=== Starting GSA Step 2 Aggregate ==="
echo "Command: Rscript --vanilla $WRAPPER_SCRIPT $CONFIG_PATH $GSA_METHOD $SAMPLE_ID"
echo ""

Rscript --vanilla "$WRAPPER_SCRIPT" "$CONFIG_PATH" "$GSA_METHOD" "$SAMPLE_ID"
EXIT_STATUS=$?

echo ""
echo "=== GSA Step 2 Aggregate Job Completed ==="
date
echo "Exit Status: $EXIT_STATUS"

exit $EXIT_STATUS
