#!/usr/bin/env Rscript
#=======================================================================================
# Generic GSA Step 2 - Aggregate QC and Index Script
#
# This script QCs Step 2 aggregation outputs:
#   - database: check weighted table row/sample count, add indexes
#   - file_system: verify all dc_aggRslt_<id>.rds exist under Aggregated_Outputs
#
# Usage: Rscript gsa_step2_aggregate_qc.R <config_path> <task_id> <n_sample>
#
# Arguments:
#   config_path  - Path to YAML configuration file
#   task_id      - GSA method index into config$gsa$gsa_methods (1-based)
#   n_sample     - Expected number of parameter sets / simulation IDs
#
# Author: Generated by Claude Code for DayCent Calibration Framework
# Date: March 2026
#=======================================================================================

# Parse command line arguments
args <- commandArgs(trailingOnly = TRUE)
if (length(args) > 0) {
    config_path <- args[1] # Path to YAML config file
    task_id <- args[2]     # Task ID (GSA method index)
    n_sample <- args[3]    # Number of samples
} else {
    # config_path <- "workflows/configs/crop_yield_corn_all.yaml"
}

# Load YAML to get custom library path (minimal setup)
if (!require(yaml, quietly = TRUE)) {
    stop("yaml package not available. Please run step0_r_setup.R first.")
}
config <- yaml::read_yaml(config_path)

# Set custom library path (packages should already be installed by step0_r_setup.R)
if (!is.null(config$r_config$rlibpaths)) {
    .libPaths(new = c(config$r_config$rlibpaths, .libPaths()))
}

# Load required packages (assuming they are already installed)
suppressPackageStartupMessages({
  library(bayesiancalibr)
})


# Validate inputs
if (!file.exists(config_path)) {
  cat("ERROR: Configuration file not found:", config_path, "\n")
  quit(status = 1)
}


# Load configuration
cat("=== Individual GSA Step 2 Aggregate QC ===\n")
cat("Loading configuration from:", config_path, "\n")

config <- tryCatch({
  read_yaml_config(config_path)
}, error = function(e) {
  cat("ERROR: Failed to load configuration:", e$message, "\n")
  quit(status = 1)
})

# Resolve paths
config <- resolve_config_paths(config)

# Expected sample count (CLI)
n_sample <- as.integer(n_sample)
if (is.na(n_sample) || n_sample <= 0) {
  cat("ERROR: n_sample must be a positive integer (args[3])\n")
  quit(status = 1)
}
cat("Expected n_sample:", n_sample, "\n")

# Set up database / file-system QC
db_result_cfg <- config$file_source$database$database_result
if (is.null(db_result_cfg)) {
  cat("Skipping result QC: database_result not in config\n")
  quit(status = 0)
}

if (identical(db_result_cfg$run_type, "database")) {

  # Set up index
  weighted_table <- config$file_source$database$database_result$tables$gsa_results_weighted
  host <- db_result_cfg$host
  database <- db_result_cfg$database
  cred_file <- db_result_cfg$cred_file %||% "~/.dblogin"

  cred <- readLines(path.expand(cred_file), warn = FALSE)
  if (length(cred) < 2) stop("Credential file must contain at least 2 lines (username, password)")
  username <- trimws(cred[1])
  password <- trimws(cred[2])

  has_mariadb <- requireNamespace("RMariaDB", quietly = TRUE)
  has_mysql <- requireNamespace("RMySQL", quietly = TRUE)
  if (!requireNamespace("DBI", quietly = TRUE)) stop("Package 'DBI' is required")
  if (!has_mariadb && !has_mysql) stop("Package 'RMariaDB' or 'RMySQL' is required")

  if (has_mariadb) {
    dbConn_postproc <- DBI::dbConnect(
      RMariaDB::MariaDB(),
      host = host, dbname = database,
      username = username, password = password
    )
  } else {
    dbConn_postproc <- DBI::dbConnect(
      RMySQL::MySQL(),
      host = host, dbname = database,
      username = username, password = password
    )
  }
  on.exit(DBI::dbDisconnect(dbConn_postproc), add = TRUE)
  cat("Connected to database\n")

  cat("Weighted table:", weighted_table, "\n")
  weighted_df <- tryCatch({
    DBI::dbGetQuery(
      dbConn_postproc,
      paste0(
        "SELECT * FROM ", weighted_table,
        " ;"
      )
    )
  }, error = function(e) {
    cat("Weighted table query failed:", conditionMessage(e), "\n")
    NULL
  })

  if (is.null(weighted_df)) {
    cat("ERROR: could not load weighted table\n")
    quit(status = 1)
  }

  id_col <- if ("sample_id" %in% names(weighted_df)) {
    "sample_id"
  } else if ("simulation_id" %in% names(weighted_df)) {
    "simulation_id"
  } else if ("SampleID" %in% names(weighted_df)) {
    "SampleID"
  } else {
    NA_character_
  }

  found_ids <- if (!is.na(id_col)) {
    unique(weighted_df[[id_col]])
  } else {
    seq_len(nrow(weighted_df))
  }
  n_found <- length(found_ids)

  if (n_found != n_sample) {
    cat("Number of weighted samples does not match expected n_sample:", n_sample, "\n")
    cat("Found unique samples:", n_found, "\n")
    if (!is.na(id_col)) {
      missing_samples <- setdiff(seq_len(n_sample), found_ids)
      if (length(missing_samples) > 0) {
        cat("Missing samples:", length(missing_samples), "\n")
        max_print <- 50L
        cat("  IDs:", paste(utils::head(sort(missing_samples), max_print), collapse = ", "))
        if (length(missing_samples) > max_print) {
          cat(" ...")
        }
        cat("\n")
      }
    }
    quit(status = 1)
  } else {
    cat("Number of weighted samples matches expected n_sample:", n_sample, "\n")

    # Indexing
    add_index_if_missing <- function(conn, table_name, index_name, column_name) {
      existing_index <- DBI::dbGetQuery(
        conn,
        paste0("SHOW INDEX FROM ", table_name, " WHERE Key_name = '", index_name, "'")
      )

      if (nrow(existing_index) > 0) {
        cat("Index already exists, skipping:", index_name, "\n")
        return(invisible(FALSE))
      }

      tryCatch({
        DBI::dbExecute(
          conn,
          paste0("ALTER TABLE ", table_name, " ADD INDEX ", index_name, " (", column_name, ");")
        )
        cat("Index created:", index_name, "\n")
        invisible(TRUE)
      }, error = function(e) {
        cat("Index creation failed, continuing:", index_name, "-", conditionMessage(e), "\n")
        invisible(FALSE)
      })
    }

    add_index_if_missing(dbConn_postproc, weighted_table, "idx_job", "job_group")
    add_index_if_missing(dbConn_postproc, weighted_table, "idx_simulation", "simulation_id")

    DBI::dbDisconnect(dbConn_postproc)
    cat("Disconnected from database\n")
  }

} else if (identical(db_result_cfg$run_type, "file_system")) {
  cat("Run type: file_system\n")

  # Resolve GSA method (path includes method folder)
  if (exists("task_id") && !is.null(task_id) && !is.na(task_id) && nzchar(as.character(task_id))) {
    task_id_num <- as.integer(task_id)
  } else if (!is.null(config$gsa$task_id)) {
    task_id_num <- as.integer(config$gsa$task_id)
  } else {
    task_id_num <- 6L
    cat("task_id not provided; defaulting to 6 (soboljansen)\n")
  }
  gsa_methods <- config$gsa$gsa_methods
  if (is.na(task_id_num) || task_id_num < 1L || task_id_num > length(gsa_methods)) {
    cat("ERROR: task_id must be an integer from 1 to", length(gsa_methods), "\n")
    quit(status = 1)
  }
  gsa_method <- gsa_methods[[task_id_num]]

  # Paths: {lairice_root}/{output_base}/{date}/GSA/{method}/Aggregated_Outputs
  # e.g. results/crop_yield_corn_m4/07Apr2026/GSA/soboljansen/Aggregated_Outputs
  # (GSA uses a method subfolder; SIR uses .../SIR/Aggregated_Outputs)
  date_stamp <- config$project$date_stamp
  if (identical(date_stamp, "auto")) {
    date_stamp <- format(Sys.Date(), "%d%b%Y")
  }
  lairice_root <- config$paths$lairice_root
  output_base <- if (!is.null(config$paths$output_base)) config$paths$output_base else "."
  agg_dir_name <- config$output_dirs$aggregated_outputs %||% "Aggregated_Outputs"
  gsa_method_dir <- file.path(lairice_root, output_base, date_stamp, "GSA", gsa_method)
  aggregated_outputs_path <- file.path(gsa_method_dir, agg_dir_name)

  file_prefix <- "dc_aggRslt_"

  cat("==============================================\n")
  cat("File-system Aggregated_Outputs QC\n")
  cat("==============================================\n")
  cat("GSA method:", gsa_method, "\n")
  cat("Aggregated_Outputs path:", aggregated_outputs_path, "\n")
  cat("Expected files:", n_sample, "(sim IDs 1 to", n_sample, ")\n")
  cat("File pattern:", paste0(file_prefix, "<id>.rds"), "\n")
  cat("  id may be integer (100000) or R scientific notation (1e+05)\n\n")

  if (!dir.exists(aggregated_outputs_path)) {
    cat("ERROR: Aggregated_Outputs directory does not exist:", aggregated_outputs_path, "\n")
    quit(status = 1)
  }

  # id tokens: plain digits or sci notation (1e+05)
  id_token_re <- "[0-9]+(?:[eE][+-]?[0-9]+)?"
  file_name_re <- paste0("^", file_prefix, "(", id_token_re, ")(?:_part\\d+)?\\.rds$")

  job_dirs <- list.dirs(aggregated_outputs_path, recursive = FALSE, full.names = TRUE)
  job_dirs <- job_dirs[grepl("^jobGroup_", basename(job_dirs))]
  search_dirs <- if (length(job_dirs) > 0) job_dirs else aggregated_outputs_path

  cat("Scanning", length(search_dirs), "directories...\n")

  found_file_numbers <- integer(0)
  for (search_dir in search_dirs) {
    files <- list.files(
      search_dir,
      pattern = file_name_re,
      full.names = FALSE
    )
    if (length(files) == 0) next
    id_str <- sub(file_name_re, "\\1", files)
    file_numbers <- as.integer(as.numeric(id_str))
    file_numbers <- file_numbers[!is.na(file_numbers)]
    found_file_numbers <- c(found_file_numbers, file_numbers)
  }

  found_file_numbers <- sort(unique(found_file_numbers))
  expected_file_numbers <- seq_len(n_sample)
  missing_file_numbers <- setdiff(expected_file_numbers, found_file_numbers)
  extra_file_numbers <- setdiff(found_file_numbers, expected_file_numbers)

  total_found <- length(found_file_numbers)
  total_missing <- length(missing_file_numbers)
  completion_rate <- if (n_sample > 0) {
    round(100 * total_found / n_sample, 2)
  } else {
    NA_real_
  }

  find_consecutive_ranges <- function(numbers) {
    if (length(numbers) == 0) return(list())
    ranges <- list()
    start <- numbers[1]
    end <- numbers[1]
    for (i in seq_along(numbers)[-1]) {
      if (numbers[i] == end + 1L) {
        end <- numbers[i]
      } else {
        ranges[[length(ranges) + 1L]] <- list(start = start, end = end, count = end - start + 1L)
        start <- numbers[i]
        end <- numbers[i]
      }
    }
    ranges[[length(ranges) + 1L]] <- list(start = start, end = end, count = end - start + 1L)
    ranges
  }

  cat("\n=== Aggregated_Outputs Summary ===\n")
  cat("Files found:", total_found, "/", n_sample, "(", completion_rate, "%)\n")
  cat("Files missing:", total_missing, "\n")
  if (length(extra_file_numbers) > 0) {
    cat("Extra file IDs outside 1:n_sample:", length(extra_file_numbers), "\n")
  }

  if (total_missing > 0) {
    cat("\nMissing simulation ID ranges:\n")
    ranges <- find_consecutive_ranges(missing_file_numbers)
    max_print <- 50L
    n_print <- min(length(ranges), max_print)
    for (i in seq_len(n_print)) {
      r <- ranges[[i]]
      if (r$start == r$end) {
        cat("  ", r$start, "\n")
      } else {
        cat("  ", r$start, "-", r$end, " (", r$count, " files)\n")
      }
    }
    if (length(ranges) > max_print) {
      cat("  ... and", length(ranges) - max_print, "more ranges\n")
    }

    qc_dir_name <- config$output_dirs$qc_outputs %||% "QC_Outputs"
    qc_dir <- file.path(gsa_method_dir, qc_dir_name)
    if (!dir.exists(qc_dir)) dir.create(qc_dir, recursive = TRUE, showWarnings = FALSE)
    missing_file <- file.path(qc_dir, "gsa_step2_missing_aggregated_outputs.csv")
    utils::write.csv(
      data.frame(simulation_id = missing_file_numbers),
      missing_file,
      row.names = FALSE
    )
    cat("\nMissing IDs written to:", missing_file, "\n")
    cat("QC FAILED: missing aggregated output files detected\n")
    quit(status = 1)
  }

  cat("\nQC PASSED: all", n_sample, "aggregated output files are present\n")

} else {
  cat(
    "ERROR: Unsupported run_type:",
    if (is.null(db_result_cfg$run_type)) "NULL" else db_result_cfg$run_type,
    "\nExpected 'database' or 'file_system'\n"
  )
  quit(status = 1)
}
