#!/usr/bin/env Rscript
#=======================================================================================
# Generic GSA Step 2 - Individual Simulation Wrapper Script
#
# This script processes ONE individual Monte Carlo simulation using the new
# specification-driven generic framework. Each call processes a single simulation ID.
#
# Usage: Rscript gsa_step2_simulate.R <config_path> <gsa_method> <sim_id> [daycent_exe] [scratch_dir]
#
# Arguments:
#   config_path  - Path to YAML configuration file
#   gsa_method   - GSA method name (e.g., soboljansen, sobol, etc.)
#   sim_id       - Individual simulation ID (1 to MC_nsim)
#   daycent_exe  - Optional: Path to DayCent executable (defaults to config)
#   scratch_dir  - Optional: Scratch directory path (defaults to /tmp/daycent_<pid>)
#
# Author: Generated by Claude Code for DayCent Calibration Framework
# Date: July 2025
#=======================================================================================

# Parse command line arguments
args <- commandArgs(trailingOnly = TRUE)
if (length(args) > 0) {
    config_path <- args[1] # Path to YAML config file
} else {
    config_path <- "workflows/configs/crop_yield_corn_all.yaml"
}

# Load YAML to get custom library path (minimal setup)
if (!require(yaml, quietly = TRUE)) {
    stop("yaml package not available. Please run step0_r_setup.R first.")
}
config <- yaml::read_yaml(config_path)

# Set custom library path (packages should already be installed by step0_r_setup.R)
if (!is.null(config$r_config$rlibpaths)) {
    .libPaths(new = c(config$r_config$rlibpaths, .libPaths()))
}

# Load required packages (assuming they are already installed)
suppressPackageStartupMessages({
  library(bayesiancalibr)
})

# Continue with argument parsing
if (length(args) > 0) {
    gsa_method <- args[2] # GSA method name
    sim_id <- as.numeric(args[3]) # Individual simulation ID

    cat("Running GSA Step 2 with command line arguments:\n")
    cat("Config file:", config_path, "\n")
    cat("GSA method:", gsa_method, "\n")
    cat("Simulation ID:", sim_id, "\n")
    
    # Parse optional --partition-id argument for scaling mode
    partition_id_override <- NULL
    if ("--partition-id" %in% args) {
      partition_id_idx <- which(args == "--partition-id")
      if (length(args) > partition_id_idx) {
        partition_id_override <- as.integer(args[partition_id_idx + 1])
        cat("Partition ID override:", partition_id_override, "(Scaling mode partition filtering)\n")
      }
    }
    cat("\n")
    
    # Optional arguments
    daycent_exe <- if(length(args) >= 4 && !grepl("^--", args[4])) args[4] else NULL
    scratch_dir <- if(length(args) >= 5 && !grepl("^--", args[5])) args[5] else NULL
} else {
    # Example 2: Interactive usage with defaults
    # config_path <- "workflows/configs/soil_organic_carbon.yaml" # change config file for different project
    gsa_method <- "soboljansen" # Default method to match step1's task_id = 6
    sim_id <- 1 # Default simulation ID for testing

    cat("Running GSA Step 2 with default configuration:\n")
    cat("Config file:", config_path, "\n")
    cat("GSA method:", gsa_method, "\n")
    cat("Simulation ID:", sim_id, "\n\n")
    
    # Optional arguments set to NULL for defaults
    partition_id_override <- NULL  # Legacy mode (no partition filtering)
    daycent_exe <- NULL  # Let the path construction logic handle this
    scratch_dir <- NULL  # Let the default logic handle this
}

# Validate inputs
if (!file.exists(config_path)) {
  cat("ERROR: Configuration file not found:", config_path, "\n")
  quit(status = 1)
}

if (is.na(sim_id) || sim_id < 1) {
  cat("ERROR: sim_id must be a positive integer, got:", sim_id, "\n")
  quit(status = 1)
}

# Validate GSA method
valid_methods <- c("sobol", "sobol2002", "sobolSaltA", "sobolSaltB", 
                   "sobol2007", "soboljansen", "sobolmartinez", "sobolEff")
if (!gsa_method %in% valid_methods) {
  cat("ERROR: Invalid GSA method:", gsa_method, "\n")
  cat("Valid methods:", paste(valid_methods, collapse = ", "), "\n")
  quit(status = 1)
}

# Load configuration
cat("=== Individual GSA Step 2 Simulation ===\n")
cat("Loading configuration from:", config_path, "\n")

config <- tryCatch({
  read_yaml_config(config_path)
}, error = function(e) {
  cat("ERROR: Failed to load configuration:", e$message, "\n")
  quit(status = 1)
})

# Resolve paths
config <- resolve_config_paths(config)

# Set up DayCent executable path
if (is.null(daycent_exe)) {
  if ("daycent" %in% names(config) && "executable" %in% names(config$daycent)) {
    daycent_exe <- file.path(config$paths$lairice_root, config$daycent$executable)
  } else {
    cat("ERROR: DayCent executable not specified in config or command line\n")
    quit(status = 1)
  }
}

# Set up scratch directory
if (is.null(scratch_dir)) {
  if ("cluster" %in% names(config) && "scratch_dir" %in% names(config$cluster)) {
    if (!file.path.is.absolute(config$cluster$scratch_dir)) {
      scratch_dir <- file.path(config$paths$lairice_root, config$cluster$scratch_dir)
    } else {
      scratch_dir <- config$cluster$scratch_dir
    }
  } else {
    scratch_dir <- "/scratch/daycent_calibration"  # fallback default
  }
}

# Display run information
cat("Project:", config$project$name, "\n")
cat("GSA Method:", gsa_method, "\n")
cat("Simulation ID:", sim_id, "\n")
cat("DayCent executable:", daycent_exe, "\n")
cat("Scratch directory:", scratch_dir, "\n")
cat("Configuration validated successfully\n")

# Record start time
start_time <- Sys.time()
cat("Starting simulation at:", format(start_time), "\n")

# Determine connection pooling strategy
# For database mode, estimate expected operations based on typical site count
# This will auto-enable pooling for jobs with >1 database operation (based on threshold)
pooling_strategy <- determine_pooling_strategy(
  config = config,
  expected_operations = 451 * 6,  # Estimate: 451 sites × 6 connections per site
  log_function = cat
)

# Create shared database connection if pooling is enabled
shared_connection <- NULL
if (pooling_strategy$use_pooling) {
  cat("Creating shared database connection for connection pooling...\n")
  shared_connection <- get_shared_connection(
    config = config,
    log_function = cat
  )
  if (!is.null(shared_connection)) {
    cat("✓ Shared connection created - will reuse across all sites\n")
  } else {
    cat("⚠ Failed to create shared connection - falling back to individual connections\n")
  }
}

# Run individual simulation using generic approach
cat("\n=== Running Individual GSA Step 2 Simulation (Generic) ===\n")
result <- tryCatch({
  # Call the generic function that uses specification-driven processing
  gsa_step2_simulate_individual_generic(
    config = config,
    gsa_method = gsa_method,
    sim_id = sim_id,
    daycent_exe = daycent_exe,
    scratch_dir = scratch_dir,
    clean_scratch = config$cluster$clean_scratch,
    start_id = 0,
    partition_id_override = partition_id_override,  # Pass for scaling mode
    shared_connection = shared_connection,  # Pass shared connection for pooling
    verbose = TRUE
  )
}, error = function(e) {
  cat("ERROR: Individual GSA Step 2 simulation failed:", e$message, "\n")
  # Clean up shared connection on error
  if (!is.null(shared_connection)) {
    close_shared_connection(config, log_function = cat)
  }
  quit(status = 1)
})

# Record end time and duration
end_time <- Sys.time()
duration <- end_time - start_time
cat("\n=== Simulation Complete ===\n")
cat("End time:", format(end_time), "\n")
cat("Duration:", format(duration), "\n")

# Display results summary
if (result$status == 0) {
  cat("Status: SUCCESS\n")
  cat("Simulation ID processed:", result$sim_id, "\n")
  
  if (!is.null(result$daily_results)) {
    cat("Daily results shape:", nrow(result$daily_results), "rows x", ncol(result$daily_results), "columns\n")
  }
  
  if (!is.null(result$aggregated_results)) {
    cat("Aggregated results shape:", nrow(result$aggregated_results), "rows x", ncol(result$aggregated_results), "columns\n")
  }
  
  if (!is.null(result$runtime_info)) {
    cat("Runtime information: 1 simulation record\n")
  }
  
  if (!is.null(result$output_files) && length(result$output_files) > 0) {
    cat("Output files created:\n")
    for (i in seq_along(result$output_files)) {
      cat("  ", names(result$output_files)[i], ":", result$output_files[[i]], "\n")
    }
  }

  cat("\nIndividual GSA Step 2 simulation completed successfully!\n")

  # Clean up shared connection on success
  if (!is.null(shared_connection)) {
    close_shared_connection(config, log_function = cat)
  }

  quit(status = 0)

} else {
  cat("Status: FAILED\n")
  cat("Individual GSA Step 2 simulation failed with status code:", result$status, "\n")

  # Clean up shared connection on failure
  if (!is.null(shared_connection)) {
    close_shared_connection(config, log_function = cat)
  }

  quit(status = 1)
}