#!/usr/bin/env Rscript
#=======================================================================================
# Generic GSA Step 2 - Individual Simulation Wrapper QC and Index Script
#
# This script QCs Step 2 outputs for one GSA method (via task_id) and run_type:
#   - database: check run status and add indexes on partition annual tables
#   - file_system: verify all dc_annualRslt_<id>.rds files exist under Annual_Outputs
#
# Usage: Rscript gsa_step2_simulate_qc.R <config_path> <partition_id> <task_id>
#
# Arguments:
#   config_path   - Path to YAML configuration file
#   partition_id  - Partition ID (database mode)
#   task_id       - GSA method index into config$gsa$gsa_methods (1-based)
#
# Author: Generated by Claude Code for DayCent Calibration Framework
# Date: March 2026
#=======================================================================================

# Parse command line arguments
args <- commandArgs(trailingOnly = TRUE)
if (length(args) > 0) {
    config_path <- args[1] # Path to YAML config file
    partition_id <- args[2] # Partition ID
    task_id <- args[3] # Task ID (GSA method index)
    n_sample <- args[4] # Number of samples
} else {
    # config_path <- "workflows/configs/crop_yield_corn_all.yaml"
}

# Load YAML to get custom library path (minimal setup)
if (!require(yaml, quietly = TRUE)) {
    stop("yaml package not available. Please run step0_r_setup.R first.")
}
config <- yaml::read_yaml(config_path)

cat("Task ID:", task_id, "\n")
cat("Partition ID:", partition_id, "\n")
# Set custom library path (packages should already be installed by step0_r_setup.R)
if (!is.null(config$r_config$rlibpaths)) {
    .libPaths(new = c(config$r_config$rlibpaths, .libPaths()))
}

# Load required packages (assuming they are already installed)
suppressPackageStartupMessages({
  library(bayesiancalibr)
})


# Validate inputs
if (!file.exists(config_path)) {
  cat("ERROR: Configuration file not found:", config_path, "\n")
  quit(status = 1)
}


# Load configuration
cat("=== Individual GSA Step 2 Simulation QC ===\n")
cat("Loading configuration from:", config_path, "\n")

config <- tryCatch({
  yaml::read_yaml(config_path)
}, error = function(e) {
  cat("ERROR: Failed to load configuration:", e$message, "\n")
  quit(status = 1)
})

# Resolve paths
config <- resolve_config_paths(config)

# Resolve GSA method from task_id
task_id_num <- as.integer(task_id)
gsa_methods <- config$gsa$gsa_methods
if (is.na(task_id_num) || task_id_num < 1L || task_id_num > length(gsa_methods)) {
  cat("ERROR: task_id must be an integer from 1 to", length(gsa_methods), "\n")
  quit(status = 1)
}
gsa_method <- gsa_methods[[task_id_num]]
cat("GSA method:", gsa_method, "\n")

# Set up database / file-system QC
db_result_cfg <- config$file_source$database$database_result
if (is.null(db_result_cfg)) {
  cat("Skipping result QC: database_result not in config\n")
  quit(status = 0)
}

if (identical(db_result_cfg$run_type, "database")) {

  annual_table <- db_result_cfg$tables$gsa_results_annual
  host <- db_result_cfg$host
  database <- db_result_cfg$database
  cred_file <- db_result_cfg$cred_file %||% "~/.dblogin"

  cred <- readLines(path.expand(cred_file), warn = FALSE)
  if (length(cred) < 2) stop("Credential file must contain at least 2 lines (username, password)")
  username <- trimws(cred[1])
  password <- trimws(cred[2])

  has_mariadb <- requireNamespace("RMariaDB", quietly = TRUE)
  has_mysql <- requireNamespace("RMySQL", quietly = TRUE)
  if (!requireNamespace("DBI", quietly = TRUE)) stop("Package 'DBI' is required")
  if (!has_mariadb && !has_mysql) stop("Package 'RMariaDB' or 'RMySQL' is required")

  if (has_mariadb) {
    dbConn_postproc <- DBI::dbConnect(
      RMariaDB::MariaDB(),
      host = host, dbname = database,
      username = username, password = password
    )
  } else {
    dbConn_postproc <- DBI::dbConnect(
      RMySQL::MySQL(),
      host = host, dbname = database,
      username = username, password = password
    )
  }
  on.exit(DBI::dbDisconnect(dbConn_postproc), add = TRUE)
  cat("Connected to database\n")

  # QC run status:
  # status = 0 success, status = 1 error.
  # For a given (partition_id, SampleID):
  #   - both 0 and 1 present -> error was retried successfully; ignore
  #   - only status = 1 present -> unresolved failure; report warning
  run_status_base <- db_result_cfg$tables$gsa_results_run_status
  if (is.null(run_status_base) || !nzchar(run_status_base)) {
    cat("Skipping run status QC: gsa_results_run_status not configured\n")
  } else {
    run_status_table_name <- paste0("part", partition_id, "_", run_status_base)
    cat("Run status table:", run_status_table_name, "\n")

    run_status_df <- tryCatch({
      DBI::dbGetQuery(
        dbConn_postproc,
        paste0(
          "SELECT * FROM ", run_status_table_name,
          " WHERE partition_id = ", partition_id, " ;"
        )
      )
    }, error = function(e) {
      cat("Run status query failed (continuing):", conditionMessage(e), "\n")
      NULL
    })

    if (is.null(run_status_df)) {
      cat("WARNING: could not load run status for partition_id:", partition_id, "\n")
    } else if (nrow(run_status_df) == 0) {
      cat("WARNING: no run status rows found for partition_id:", partition_id, "\n")
    } else {
      error_ids <- unique(run_status_df$SampleID[run_status_df$status == 1])
      success_ids <- unique(run_status_df$SampleID[run_status_df$status == 0])

      resolved_error_ids <- intersect(error_ids, success_ids)
      unresolved_error_ids <- setdiff(error_ids, success_ids)

      if (length(error_ids) == 0) {
        cat("No error status (status=1) found for partition_id:", partition_id, "\n")
      } else {
        if (length(resolved_error_ids) > 0) {
          cat(
            "Ignoring", length(resolved_error_ids),
            "SampleID(s) with both status=1 and status=0",
            "(retried successfully) for partition_id:", partition_id, "\n"
          )
        }

        if (length(unresolved_error_ids) > 0) {
          cat(
            "WARNING: unresolved errors (status=1 only, no status=0) for",
            length(unresolved_error_ids),
            "SampleID(s) in partition_id:", partition_id, "\n"
          )
          max_print <- 50L
          ids_to_print <- utils::head(sort(unresolved_error_ids), max_print)
          cat("  SampleIDs:", paste(ids_to_print, collapse = ", "))
          if (length(unresolved_error_ids) > max_print) {
            cat(" ... (+", length(unresolved_error_ids) - max_print, " more)")
          }
          cat("\n")
        } else {
          cat(
            "All status=1 rows are paired with status=0 for the same SampleID;",
            "no unresolved errors for partition_id:", partition_id, "\n"
          )
        }
      }
    }
  }

  # indexing
  annual_table <- paste0("part", partition_id, "_", db_result_cfg$tables$gsa_results_annual)
  cat("Annual table:", annual_table, "\n")

  add_index_if_missing <- function(conn, table_name, index_name, column_name) {
    existing_index <- DBI::dbGetQuery(
      conn,
      paste0("SHOW INDEX FROM ", table_name, " WHERE Key_name = '", index_name, "'")
    )

    if (nrow(existing_index) > 0) {
      cat("Index already exists, skipping:", index_name, "\n")
      return(invisible(FALSE))
    }

    tryCatch({
      DBI::dbExecute(
        conn,
        paste0("ALTER TABLE ", table_name, " ADD INDEX ", index_name, " (", column_name, ");")
      )
      cat("Index created:", index_name, "\n")
      invisible(TRUE)
    }, error = function(e) {
      cat("Index creation failed, continuing:", index_name, "-", conditionMessage(e), "\n")
      invisible(FALSE)
    })
  }

  # add_index_if_missing(dbConn_postproc, annual_table, "idx_job", "job_group")
  add_index_if_missing(dbConn_postproc, annual_table, "idx_id", "simulation_id")
  # add_index_if_missing(dbConn_postproc, annual_table, "idx_partition", "partition_id")
  # add_index_if_missing(dbConn_postproc, annual_table, "idx_sample", "SampleID")

  DBI::dbDisconnect(dbConn_postproc)
  cat("Disconnected from database\n")

} else if (identical(db_result_cfg$run_type, "file_system")) {
  cat("Run type: file_system\n")

  # Paths
  date_stamp <- config$project$date_stamp
  if (identical(date_stamp, "auto")) {
    date_stamp <- format(Sys.Date(), "%d%b%Y")
  }
  lairice_root <- config$paths$lairice_root
  output_base <- if (!is.null(config$paths$output_base)) config$paths$output_base else "."
  annual_dir_name <- config$output_dirs$annual_outputs %||% "Annual_Outputs"
  gsa_method_dir <- file.path(lairice_root, output_base, date_stamp, "GSA", gsa_method)
  annual_outputs_path <- file.path(gsa_method_dir, annual_dir_name)

  # Prefer actual MC draw count (Sobol designs expand beyond gsa$nsim)
  mc_file <- file.path(gsa_method_dir, paste0("mc_GSA_draw_", gsa_method, ".rds"))
  if (file.exists(mc_file)) {
    X <- readRDS(mc_file)
    expected_total_files <- nrow(X)
    cat("Expected file count from MC draws:", expected_total_files, "\n")
  } else {
    expected_total_files <- config$gsa$nsim
    cat("MC draw file not found; using config$gsa$nsim =", expected_total_files, "\n")
  }
  file_prefix <- "dc_annualRslt_"

  cat("==============================================\n")
  cat("File-system Annual_Outputs QC\n")
  cat("==============================================\n")
  cat("GSA method:", gsa_method, "\n")
  cat("Annual_Outputs path:", annual_outputs_path, "\n")
  cat("Expected files:", expected_total_files, "(sim IDs 1 to", expected_total_files, ")\n")
  cat("File pattern:", paste0(file_prefix, "<id>.rds"), "\n")
  cat("  id may be integer (100000) or R scientific notation (1e+05)\n\n")

  if (!dir.exists(annual_outputs_path)) {
    cat("ERROR: Annual_Outputs directory does not exist:", annual_outputs_path, "\n")
    quit(status = 1)
  }

  # id tokens: plain digits (123) or sci notation (1e+05, 2e+05, 1E05)
  # Matches filenames such as:
  #   dc_annualRslt_100000.rds
  #   dc_annualRslt_1e+05.rds
  #   dc_annualRslt_1e+05_part1.rds
  id_token_re <- "[0-9]+(?:[eE][+-]?[0-9]+)?"
  file_name_re <- paste0("^", file_prefix, "(", id_token_re, ")(?:_part\\d+)?\\.rds$")

  # Collect found simulation IDs from jobGroup_* subdirs (or top-level if flat)
  job_dirs <- list.dirs(annual_outputs_path, recursive = FALSE, full.names = TRUE)
  job_dirs <- job_dirs[grepl("^jobGroup_", basename(job_dirs))]
  search_dirs <- if (length(job_dirs) > 0) job_dirs else annual_outputs_path

  cat("Scanning", length(search_dirs), "directories...\n")

  found_file_numbers <- integer(0)
  for (search_dir in search_dirs) {
    files <- list.files(
      search_dir,
      pattern = file_name_re,
      full.names = FALSE
    )
    if (length(files) == 0) next
    # as.numeric() parses both "100000" and "1e+05" -> 100000
    id_str <- sub(file_name_re, "\\1", files)
    file_numbers <- as.integer(as.numeric(id_str))
    file_numbers <- file_numbers[!is.na(file_numbers)]
    found_file_numbers <- c(found_file_numbers, file_numbers)
  }

  found_file_numbers <- sort(unique(found_file_numbers))
  expected_file_numbers <- seq_len(expected_total_files)
  missing_file_numbers <- setdiff(expected_file_numbers, found_file_numbers)
  extra_file_numbers <- setdiff(found_file_numbers, expected_file_numbers)

  total_found <- length(found_file_numbers)
  total_missing <- length(missing_file_numbers)
  completion_rate <- if (expected_total_files > 0) {
    round(100 * total_found / expected_total_files, 2)
  } else {
    NA_real_
  }

  # Group consecutive IDs into ranges for readable output
  find_consecutive_ranges <- function(numbers) {
    if (length(numbers) == 0) return(list())
    ranges <- list()
    start <- numbers[1]
    end <- numbers[1]
    for (i in seq_along(numbers)[-1]) {
      if (numbers[i] == end + 1L) {
        end <- numbers[i]
      } else {
        ranges[[length(ranges) + 1L]] <- list(start = start, end = end, count = end - start + 1L)
        start <- numbers[i]
        end <- numbers[i]
      }
    }
    ranges[[length(ranges) + 1L]] <- list(start = start, end = end, count = end - start + 1L)
    ranges
  }

  cat("\n=== Annual_Outputs Summary ===\n")
  cat("Files found:", total_found, "/", expected_total_files, "(", completion_rate, "%)\n")
  cat("Files missing:", total_missing, "\n")
  if (length(extra_file_numbers) > 0) {
    cat("Extra file IDs outside 1:nsim:", length(extra_file_numbers), "\n")
  }

  if (total_missing > 0) {
    cat("\nMissing simulation ID ranges:\n")
    ranges <- find_consecutive_ranges(missing_file_numbers)
    # Cap printed ranges if very many
    max_print <- 50L
    n_print <- min(length(ranges), max_print)
    for (i in seq_len(n_print)) {
      r <- ranges[[i]]
      if (r$start == r$end) {
        cat("  ", r$start, "\n")
      } else {
        cat("  ", r$start, "-", r$end, " (", r$count, " files)\n")
      }
    }
    if (length(ranges) > max_print) {
      cat("  ... and", length(ranges) - max_print, "more ranges\n")
    }

    # Write full missing list under method QC_Outputs
    qc_dir_name <- config$output_dirs$qc_outputs %||% "QC_Outputs"
    qc_dir <- file.path(gsa_method_dir, qc_dir_name)
    if (!dir.exists(qc_dir)) dir.create(qc_dir, recursive = TRUE, showWarnings = FALSE)
    missing_file <- file.path(qc_dir, "gsa_step2_missing_annual_outputs.csv")
    utils::write.csv(
      data.frame(simulation_id = missing_file_numbers),
      missing_file,
      row.names = FALSE
    )
    cat("\nMissing IDs written to:", missing_file, "\n")
    cat("QC FAILED: missing annual output files detected\n")
    quit(status = 1)
  }

  cat("\nQC PASSED: all", expected_total_files, "annual output files are present\n")

} else {
  cat(
    "ERROR: Unsupported run_type:",
    if (is.null(db_result_cfg$run_type)) "NULL" else db_result_cfg$run_type,
    "\nExpected 'database' or 'file_system'\n"
  )
  quit(status = 1)
}
