#' SIR Step 2: Model Simulation Functions
#'
#' This file contains functions for Sample Importance Resampling (SIR) Step 2 model simulation
#' using the generic, configuration-driven framework. These functions follow the patterns
#' established in GSA Step 2 and SIR Step 1.
#'
#' @author Generated by Claude Code for DayCent Calibration Framework
#' @note Created July 2025

#' Prepare Parameter Set for SIR Simulation
#'
#' Creates a parameter data frame from SIR job parameters and configuration,
#' filtering for only the SIR-specific parameters.
#'
#' @param config Configuration object
#' @param job_params Job-specific parameters from SIR Monte Carlo draws
#' @param verbose Logical indicating whether to print progress
#' @return Data frame with File, Parameter, and value columns
#' @export
sir_step2_prepare_parameters <- function(config, job_params, verbose = TRUE) {
  
  # Read prior parameter file to get parameter names and file mappings
  prior_file <- config$input_files$prior_file
  if (!file.exists(prior_file)) {
    stop("Prior file not found: ", prior_file)
  }
  
  prior <- read.csv(prior_file, stringsAsFactors = FALSE)
  
  # Filter for SIR parameters only
  sir_parms <- config$sir$sir_parameters
  prior <- prior[prior$ParameterName %in% sir_parms, ]
  
  if (nrow(prior) == 0) {
    stop("No SIR parameters found in prior file. Check sir_parameters configuration.")
  }
  
  # Read default parameters if specified
  if ("default_params" %in% names(config$input_files)) {
    default_file <- config$input_files$default_params
    if (file.exists(default_file)) {
      dflt <- read.csv(default_file, stringsAsFactors = FALSE)
      dflt2 <- dflt[!(dflt$Parameter %in% prior$Parameter), ]
      dfltdf <- dflt2[, c("File", "Parameter", "Default")]
      names(dfltdf)[which(names(dfltdf) == "Default")] <- "value"
    } else {
      if (verbose) cat("Default parameters file not found, using only SIR parameters\n")
      dfltdf <- data.frame(File = character(0), Parameter = character(0), value = numeric(0))
    }
  } else {
    dfltdf <- data.frame(File = character(0), Parameter = character(0), value = numeric(0))
  }
  
  # Create parameter data frame from job parameters
  temp_df <- prior[, c("File", "Parameter")]
  
  # Extract parameter values from job_params (exclude SampleID and JobGroup columns)
  param_values <- as.numeric(job_params[, !names(job_params) %in% c("SampleID", "JobGroup")])
  temp_df$value <- param_values
  
  # Combine with default parameters
  params_df <- rbind(temp_df, dfltdf)
  
  if (verbose) {
    cat("Prepared SIR parameter set with", nrow(params_df), "parameters\n")
    cat("  SIR parameters:", nrow(temp_df), "\n")
    cat("  Default parameters:", nrow(dfltdf), "\n")
    cat("  SIR parameter names:", paste(sir_parms, collapse = ", "), "\n")
  }
  
  return(params_df)
}

#' Build common DayCent template directory (dot100, fix/fert/cult/crop, outfiles.in)
#'
#' Mirrors \code{gsa_step2_simulate_individual_generic}: one copy per simulation,
#' then each site receives this tree via \code{run_site_simulations_generic(..., common_template_dir)}.
#'
#' @param config Configuration object
#' @param params_df Full parameter data frame for this draw (SIR + defaults)
#' @param sim_dir_tid Task scratch directory (\code{SIM_<id>})
#' @param verbose Logical
#' @return Absolute path to \code{template_common}
#' @noRd
sir_step2_build_common_template_dir <- function(config, params_df, sim_dir_tid, verbose = TRUE) {
  common_template_dir <- file.path(sim_dir_tid, "template_common")
  if (dir.exists(common_template_dir)) {
    unlink(common_template_dir, recursive = TRUE)
  }
  dir.create(common_template_dir, recursive = TRUE, showWarnings = FALSE)
  if (!dir.exists(common_template_dir)) {
    stop("Failed to create common template directory: ", common_template_dir)
  }

  template_old_wd <- getwd()
  on.exit({
    if (is.character(template_old_wd) && length(template_old_wd) == 1 && nzchar(template_old_wd)) {
      try(setwd(template_old_wd), silent = TRUE)
    }
  }, add = TRUE)
  setwd(common_template_dir)

  dot100_status <- copy_dot100_files(
    dot100_directory = config$paths$dot100_path,
    simulation_directory = common_template_dir
  )
  if (dot100_status != 0) {
    stop("dot100 files copy failed when building common template directory")
  }

  fix100_params <- params_df[params_df$File == "fix.100", ]
  if (nrow(fix100_params) > 0) {
    fix_status <- update_fix100_parameters(paramsdf = fix100_params, save_copy = FALSE)
    if (fix_status != 0) {
      stop("fix.100 update failed when building common template directory")
    }
  }

  fert100_params <- params_df[params_df$File == "fert.100", ]
  if (nrow(fert100_params) > 0) {
    fert_status <- update_fert100_parameters(fert100_params, save_copy = FALSE)
    if (fert_status != 0) {
      stop("fert.100 update failed when building common template directory")
    }
  }

  cult100_params <- params_df[params_df$File == "cult.100", ]
  if (nrow(cult100_params) > 0) {
    k_clteff_params <- cult100_params[cult100_params$Parameter == "K_CLTEFF", ]
    if (nrow(k_clteff_params) > 0) {
      k_clteff_value <- k_clteff_params$value[1]
      cult_status <- update_cult100_parameters(k_clteff_value, save_copy = FALSE)
      if (cult_status != 0) {
        stop("cult.100 update failed when building common template directory")
      }
    }
  }

  crop100_params <- params_df[params_df$File == "crop.100", ]
  if (nrow(crop100_params) > 0) {
    crop_names <- get_pipeline_target_crop(config, "sir")
    if (length(crop_names) > 0) {
      for (crop_n in crop_names) {
        crop_status <- update_crop100_parameters(crop100_params, crop_n, save_copy = FALSE)
        if (crop_status != 0) {
          stop("crop.100 update failed for crop ", crop_n, " when building common template directory")
        }
      }
    } else {
      stop("crop.100 parameters found but crop name not specified in configuration. ",
           "Please add 'sir: crop: name: [CROP_NAME]' (or legacy 'daycent: crop: name') ",
           "to your configuration file.")
    }
  }

  outfiles_template <- config$model_outputs$outfiles_template %||% "nh3_outfiles.in"
  outfiles_from <- file.path(config$paths$dot100_path, outfiles_template)
  outfiles_to <- file.path(common_template_dir, "outfiles.in")
  if (file.exists(outfiles_from)) {
    file.copy(from = outfiles_from, to = outfiles_to, overwrite = TRUE)
    if (verbose) cat("Template outfiles.in copied successfully from ", outfiles_template, "\n")
  } else {
    fallback_outfiles <- file.path(config$paths$dot100_path, "no_outfiles.in")
    if (file.exists(fallback_outfiles)) {
      file.copy(from = fallback_outfiles, to = outfiles_to, overwrite = TRUE)
      warning("outfiles template not found (", outfiles_from, "); using no_outfiles.in")
    } else {
      warning("outfiles.in source file not found for template: ", outfiles_from)
    }
  }

  setwd(template_old_wd)
  return(common_template_dir)
}

#' Run Site Simulations for SIR
#'
#' Executes DayCent simulations for all treatments at all experimental sites
#' for a single SIR Monte Carlo draw using generic output processing.
#' Aligns with \code{gsa_step2_simulate_individual_generic}: common template directory,
#' optional aggregation-level weighted workflow, and \code{common_template_dir} passed
#' to \code{run_site_simulations_generic}.
#'
#' @param config Configuration object
#' @param params_df Parameter data frame for this simulation
#' @param sim_dir_tid Task-specific simulation directory
#' @param daycent_exe Path to DayCent executable
#' @param actual_sim_id Simulation ID for this run
#' @param runFile DayCent run file data frame
#' @param sir_output_path Results path for this project/date/SIR (for weighted mean outputs)
#' @param group_id Job group id (\code{JobGroup} from MC draws)
#' @param partition_id Optional partition for scaling mode site filtering
#' @param shared_connection Optional shared database connection (for connection pooling)
#' @param verbose Logical indicating whether to print progress
#' @return List with simulation results and statistics
#' @export
sir_step2_run_sites <- function(config, params_df, sim_dir_tid, daycent_exe,
                               actual_sim_id, runFile, sir_output_path, group_id,
                               partition_id = NULL,
                               shared_connection = NULL, verbose = TRUE) {

  num_sites <- 0
  num_treatments <- 0
  num_sim_years <- 0
  num_obs_years <- 0
  daily_results <- NULL
  annual_results <- NULL
  period_results <- NULL
  aggregated_results <- NULL
  weighted_mean_results <- NULL

  output_specs <- load_output_specifications(config, verbose = FALSE)
  agg_vars <- initialize_aggregated_variables_generic(output_specs, verbose = FALSE)

  exp_SiteIDs <- sort(unique(runFile$siteID))

  scaling_mode <- is_scaling_mode_enabled(config)
  if (scaling_mode && !is.null(partition_id)) {
    point_assignments_file <- file.path(sir_output_path, "point_assignments.rds")
    if (file.exists(point_assignments_file)) {
      assigned_sites <- get_assigned_sites_for_job(
        point_assignments_file,
        current_job_id = partition_id,
        verbose = verbose
      )
      exp_SiteIDs <- exp_SiteIDs[exp_SiteIDs %in% assigned_sites]
      if (verbose) {
        cat("Scaling mode with partition - filtered to", length(exp_SiteIDs), "assigned sites for partition", partition_id, "\n")
      }
    } else if (verbose) {
      cat("Warning: Scaling mode enabled but point_assignments.rds not found\n")
    }
  } else if (scaling_mode && is.null(partition_id)) {
    if (verbose) cat("Scaling mode without partition - processing ALL", length(exp_SiteIDs), "sites\n")
  }

  if (verbose) {
    cat("Processing", length(exp_SiteIDs), "sites with RunFile structure\n")
  }

  common_template_dir <- sir_step2_build_common_template_dir(config, params_df, sim_dir_tid, verbose = verbose)

  weighted_aggregation_enabled <- FALSE
  if ("variables" %in% names(output_specs)) {
    weighted_vars <- output_specs$variables[!is.na(output_specs$variables$weighted_mean_aggregation) &
                                            output_specs$variables$weighted_mean_aggregation == TRUE, ]
    if (nrow(weighted_vars) > 0 &&
        "aggregation_level" %in% names(runFile) &&
        "aggregation_weight" %in% names(runFile)) {
      weighted_aggregation_enabled <- TRUE
    }
  }

  if (weighted_aggregation_enabled && verbose) {
    cat("Weighted mean aggregation enabled - processing sites by aggregation level\n")
  }

  if (weighted_aggregation_enabled) {
    if (!("aggregation_level" %in% names(runFile))) {
      stop("RunFile missing aggregation_level column required for weighted aggregation")
    }

    runFile_filtered <- runFile[runFile$siteID %in% exp_SiteIDs, ]
    aggregation_groups <- split(runFile_filtered, runFile_filtered$aggregation_level)
    aggregation_level_names <- names(aggregation_groups)

    if (verbose) {
      cat("Processing", length(aggregation_level_names), "aggregation levels:",
          paste(aggregation_level_names, collapse = ", "), "\n")
    }

    for (level_id in aggregation_level_names) {
      level_sites <- aggregation_groups[[level_id]]
      level_site_ids <- level_sites$siteID

      if (verbose) {
        cat("Processing aggregation level", level_id, "with", length(level_site_ids), "sites\n")
      }

      for (site_id in level_site_ids) {
        num_sites <- num_sites + 1
        site_id <- trimws(site_id)
        run_file_site <- runFile[runFile$siteID == site_id, ]

        if (verbose) {
          cat("Processing site:", site_id, "in aggregation level:", level_id, "\n")
        }

        site_result <- run_site_simulations_generic(
          site_id = site_id,
          run_file_site = run_file_site,
          config = config,
          params_df = params_df,
          sim_dir_tid = sim_dir_tid,
          daycent_exe = daycent_exe,
          actual_task_id = actual_sim_id,
          agg_vars = agg_vars,
          shared_connection = shared_connection,
          common_template_dir = common_template_dir,
          verbose = verbose
        )

        num_treatments <- num_treatments + site_result$num_treatments
        num_sim_years <- num_sim_years + site_result$num_sim_years
        if (!is.null(site_result$num_obs_years)) {
          num_obs_years <- num_obs_years + site_result$num_obs_years
        }

        daily_results <- rbind(daily_results, site_result$daily_results)
        annual_results <- rbind(annual_results, site_result$annual_results)
        period_results <- rbind(period_results, site_result$period_results)

        if (is.null(aggregated_results)) {
          aggregated_results <- site_result$aggregated_results
        } else if (!is.null(site_result$aggregated_results)) {
          for (var_name in names(site_result$aggregated_results)) {
            if (var_name %in% names(aggregated_results)) {
              aggregated_results[[var_name]] <- aggregated_results[[var_name]] + site_result$aggregated_results[[var_name]]
            } else {
              aggregated_results[[var_name]] <- site_result$aggregated_results[[var_name]]
            }
          }
        }
      }

      if (verbose) {
        cat("All sites in aggregation level", level_id, "completed.\n")
      }

      tryCatch({
        if (exists("determine_cleanup_policy")) {
          cleanup_policy <- determine_cleanup_policy(output_specs$variables)
          if (!is.null(cleanup_policy$delete_annual_after_aggregation) &&
              cleanup_policy$delete_annual_after_aggregation && verbose) {
            cat("Cleanup policy: deleting annual results for aggregation level", level_id, "to save disk space\n")
          }
        } else {
          wvars <- output_specs$variables[!is.na(output_specs$variables$weighted_mean_aggregation) &
                                          output_specs$variables$weighted_mean_aggregation == TRUE, ]
          if (nrow(wvars) > 0 && any(wvars$annual_output == FALSE) && verbose) {
            cat("Note: Some weighted variables have annual_output=FALSE - cleanup would apply in production\n")
          }
        }
      }, error = function(e) {
        if (verbose) {
          cat("Warning: Cleanup policy determination failed:", e$message, "\n")
        }
      })
    }

    if (!scaling_mode && crop_calibration_enabled(config, get_pipeline_target_crop(config, "sir"))) {
      if (verbose) {
        cat("All aggregation levels completed. Performing weighted aggregation for all counties.\n")
      }

      tryCatch({
        if (exists("process_weighted_mean_aggregation_for_sample")) {
          weighted_output_dir <- file.path(sir_output_path, "Weighted_Mean_Outputs", paste0("jobGroup_", group_id))
          dir.create(weighted_output_dir, recursive = TRUE, showWarnings = FALSE)

          weighted_mean_results <- process_weighted_mean_aggregation_for_sample(
            config = config,
            target_crop = get_pipeline_target_crop(config, "sir"),
            annual_results = annual_results,
            sample_id = actual_sim_id,
            job_group = group_id,
            weighted_output_dir = weighted_output_dir,
            output_specs = output_specs$variables,
            method = "SIR",
            verbose = verbose
          )

          if (verbose) {
            cat("Weighted aggregation completed for sample", actual_sim_id, "\n")
          }
        } else if (verbose) {
          cat("Warning: process_weighted_mean_aggregation_for_sample function not available\n")
        }
      }, error = function(e) {
        stop("Weighted aggregation failed for sample ", actual_sim_id, ": ", e$message)
      })
    } else if (scaling_mode && verbose) {
      cat("Scaling mode: Skipping inline weighted aggregation (defer to SIR step 2 aggregate)\n")
    }

  } else {
    if (verbose) cat("Using standard site-by-site processing\n")

    for (i in 1:length(exp_SiteIDs)) {
      num_sites <- num_sites + 1
      site_id <- trimws(exp_SiteIDs[i])
      run_file_site <- runFile[runFile$siteID == site_id, ]

      if (verbose) {
        cat("\n*************** Running SiteID:", site_id, "***************\n")
      }

      site_result <- run_site_simulations_generic(
        site_id = site_id,
        run_file_site = run_file_site,
        config = config,
        params_df = params_df,
        sim_dir_tid = sim_dir_tid,
        daycent_exe = daycent_exe,
        actual_task_id = actual_sim_id,
        agg_vars = agg_vars,
        shared_connection = shared_connection,
        common_template_dir = common_template_dir,
        verbose = verbose
      )

      num_treatments <- num_treatments + site_result$num_treatments
      num_sim_years <- num_sim_years + site_result$num_sim_years
      if (!is.null(site_result$num_obs_years)) {
        num_obs_years <- num_obs_years + site_result$num_obs_years
      }

      daily_results <- rbind(daily_results, site_result$daily_results)
      annual_results <- rbind(annual_results, site_result$annual_results)
      period_results <- rbind(period_results, site_result$period_results)

      if (is.null(aggregated_results)) {
        aggregated_results <- site_result$aggregated_results
      } else if (!is.null(site_result$aggregated_results)) {
        for (var_name in names(site_result$aggregated_results)) {
          if (var_name %in% names(aggregated_results)) {
            aggregated_results[[var_name]] <- aggregated_results[[var_name]] + site_result$aggregated_results[[var_name]]
          } else {
            aggregated_results[[var_name]] <- site_result$aggregated_results[[var_name]]
          }
        }
      }
    }
  }

  agg_vars_specs <- output_specs$variables[output_specs$variables$aggregate_output == TRUE, ]
  if (nrow(agg_vars_specs) > 0) {
    agg_result <- create_aggregated_results_generic(aggregated_results, actual_sim_id, verbose = FALSE)
  } else {
    agg_result <- data.frame(SampleID = actual_sim_id)
  }

  if (verbose) {
    cat("\nSite simulation summary:\n")
    cat("  Sites processed:", num_sites, "\n")
    cat("  Treatments processed:", num_treatments, "\n")
    cat("  Simulation years:", num_sim_years, "\n")
    cat("  Daily results rows:", if (is.null(daily_results)) 0 else nrow(daily_results), "\n")
    cat("  Annual results rows:", if (is.null(annual_results)) 0 else nrow(annual_results), "\n")
    cat("  Weighted mean results rows:", if (is.null(weighted_mean_results)) 0 else nrow(weighted_mean_results), "\n")
  }

  return(list(
    num_sites = num_sites,
    num_treatments = num_treatments,
    num_sim_years = num_sim_years,
    num_obs_years = num_obs_years,
    daily_results = daily_results,
    annual_results = annual_results,
    period_results = period_results,
    aggregated_results = agg_result,
    weighted_mean_results = weighted_mean_results
  ))
}

#' SIR Step 2 Simulate Individual
#'
#' Processes a single SIR Monte Carlo simulation using the generic framework.
#' This function handles one simulation ID from the SIR Monte Carlo draws.
#'
#' @param config A complete YAML configuration object loaded with read_yaml_config()
#' @param sim_id The simulation ID for this SIR instance
#' @param daycent_exe Path to DayCent executable file
#' @param scratch_dir Scratch directory for temporary simulation files
#' @param clean_scratch Logical indicating whether to clean scratch files after simulation
#' @param start_id Starting ID offset for simulation numbering (default: 0)
#' @param shared_connection Optional shared database connection (for connection pooling)
#' @param verbose Logical indicating whether to print progress messages (default: TRUE)
#' @return List containing simulation results and status information
#' @export
sir_step2_simulate_individual <- function(config, sim_id, daycent_exe, scratch_dir,
                                        clean_scratch = TRUE, start_id = 0,
                                        partition_id_override = NULL,
                                        shared_connection = NULL, verbose = TRUE) {
  
  # Initialize timing and status tracking
  start_time <- Sys.time()
  node <- Sys.info()[4]
  complete <- FALSE
  
  # Detect execution mode
  scaling_mode <- is_scaling_mode_enabled(config)
  
  # Determine partition_id and actual_sim_id based on mode and arguments
  # Key change: sim_id is ALWAYS the SampleID (matches legacy behavior)
  actual_sim_id <- start_id + sim_id
  
  if (scaling_mode && !is.null(partition_id_override)) {
    # Scaling mode WITH partition specified: filter to partition subset
    partition_id <- partition_id_override
    
  } else if (scaling_mode && is.null(partition_id_override)) {
    # Scaling mode WITHOUT partition: run ALL sites (legacy behavior for this sample)
    partition_id <- NULL
    
  } else {
    # Legacy mode: no partition filtering
    partition_id <- NULL
  }
  
  # Initialize output variables
  output_result <- list(
    status = 1,  # Default to error
    daily_results = NULL,
    annual_results = NULL,  # Add annual_results initialization
    aggregated_results = NULL,
    weighted_mean_results = NULL,  # Add weighted_mean_results initialization
    runtime_info = NULL,
    sim_id = actual_sim_id,
    partition_id = partition_id,
    scaling_mode = scaling_mode,
    output_files = list()
  )
  
  if (verbose) {
    cat("====================================================================\n")
    cat("SIR Step 2 - Individual Simulation\n")
    cat("Node:", node, "\n")
    cat("Working Directory:", getwd(), "\n\n")
    cat("Configuration:\n")
    cat("\t Project Name                :", config$project$name, "\n")
    cat("\t Execution Mode              :", if(scaling_mode) "SCALING" else "LEGACY", "\n")
    cat("\t Simulation ID (SampleID)    :", actual_sim_id, "\n")
    if (!is.null(partition_id)) {
      cat("\t Partition ID (filtering)    :", partition_id, "\n")
    } else if (scaling_mode) {
      cat("\t Partition ID                : ALL (no filtering)\n")
    }
    cat("\t DayCent Executable          :", daycent_exe, "\n")
    cat("\t Scratch Directory           :", scratch_dir, "\n")
    cat("\t Clean Scratch               :", clean_scratch, "\n\n")
    cat("====================================================================\n")
  }
  
  # Main simulation logic in tryCatch
  tryCatch({
    
    # Determine date stamp
    if (config$project$date_stamp == "auto") {
      date_stamp <- format(Sys.Date(), "%d%b%Y")
    } else {
      date_stamp <- config$project$date_stamp
    }
    
    # Setup paths for SIR
    sir_output_path <- file.path(config$paths$lairice_root, "results", config$project$name, 
                                date_stamp, "SIR")
    sim_dir_tid <- file.path(scratch_dir, paste0("SIM_", actual_sim_id))
    
    # Create directories
    dir.create(sim_dir_tid, recursive = TRUE, showWarnings = FALSE)
    if (!dir.exists(sim_dir_tid)) {
      stop("Failed to create simulation scratch directory: ", sim_dir_tid)
    }
    
    # Load SIR Monte Carlo parameter draws
    mc_draws_file <- file.path(sir_output_path, "mc_SIR_draw.rds")
    if (!file.exists(mc_draws_file)) {
      stop("SIR Monte Carlo draws file not found: ", mc_draws_file)
    }
    
    all_jobs <- readRDS(mc_draws_file)
    
    # Get parameter set for this simulation
    if (!(actual_sim_id %in% all_jobs$SampleID)) {
      stop("Simulation ID ", actual_sim_id, " not found in SIR MC draws")
    }
    
    # Extract job parameters including JobGroup
    job_params <- all_jobs[all_jobs$SampleID == actual_sim_id, ]
    group_id <- job_params$JobGroup
    
    if (verbose) cat("Job Group:", group_id, "\n")
    
    # Prepare parameters for SIR simulation
    params_df <- sir_step2_prepare_parameters(config, job_params, verbose = verbose)
    
    # Load RunFile.rds
    run_file_name <- file.path(sir_output_path, "RunFile.rds")
    if (!file.exists(run_file_name)) {
      stop("RunFile.rds not found: ", run_file_name)
    }
    
    runFile <- readRDS(run_file_name)
    
    if (verbose) cat("RunFile loaded with", nrow(runFile), "treatment records\n")
    
    site_results <- sir_step2_run_sites(
      config = config,
      params_df = params_df,
      sim_dir_tid = sim_dir_tid,
      daycent_exe = daycent_exe,
      actual_sim_id = actual_sim_id,
      runFile = runFile,
      sir_output_path = sir_output_path,
      group_id = group_id,
      partition_id = partition_id,
      shared_connection = shared_connection,
      verbose = verbose
    )

    scaling_mode <- is_scaling_mode_enabled(config)

    db_result_cfg <- config$file_source$database$database_result
    sir_db_run_type <- if (!is.null(db_result_cfg) && !is.null(db_result_cfg$run_type)) {
      db_result_cfg$run_type
    } else {
      "file_system"
    }

    daily_output_file <- NULL
    agg_output_file <- NULL
    annual_output_file <- NULL
    weighted_mean_output_file <- NULL
    runtime_file <- NULL

    if (sir_db_run_type == "file_system") {
      daily_output_dir <- file.path(sir_output_path, "Daily_Outputs", paste0("jobGroup_", group_id))
      agg_output_dir <- file.path(sir_output_path, "Aggregated_Outputs", paste0("jobGroup_", group_id))
      annual_output_dir <- file.path(sir_output_path, "Annual_Outputs", paste0("jobGroup_", group_id))
      period_output_dir <- file.path(sir_output_path, "Period_Outputs", paste0("jobGroup_", group_id))
      weighted_mean_output_dir <- file.path(sir_output_path, "Weighted_Mean_Outputs", paste0("jobGroup_", group_id))
      run_status_dir <- file.path(sir_output_path, "Run_Status", paste0("jobGroup_", group_id))

      dir.create(daily_output_dir, recursive = TRUE, showWarnings = FALSE)
      dir.create(agg_output_dir, recursive = TRUE, showWarnings = FALSE)
      dir.create(annual_output_dir, recursive = TRUE, showWarnings = FALSE)
      dir.create(period_output_dir, recursive = TRUE, showWarnings = FALSE)
      dir.create(weighted_mean_output_dir, recursive = TRUE, showWarnings = FALSE)
      dir.create(run_status_dir, recursive = TRUE, showWarnings = FALSE)

      daily_output_file <- file.path(daily_output_dir, paste0("dc_dRslt_", actual_sim_id, ".rds"))
      if (!is.null(site_results$daily_results) && nrow(site_results$daily_results) > 0) {
        saveRDS(site_results$daily_results, daily_output_file)
      }

      agg_output_file <- file.path(agg_output_dir, paste0("dc_aggRslt_", actual_sim_id, ".rds"))
      if (!is.null(site_results$aggregated_results) && nrow(site_results$aggregated_results) > 0 &&
          ncol(site_results$aggregated_results) > 1) {
        saveRDS(site_results$aggregated_results, agg_output_file)
      }

      if (scaling_mode && !is.null(partition_id)) {
        annual_output_file <- file.path(annual_output_dir,
          paste0("dc_annualRslt_", actual_sim_id, "_part", partition_id, ".rds"))
      } else {
        annual_output_file <- file.path(annual_output_dir,
          paste0("dc_annualRslt_", actual_sim_id, ".rds"))
      }

      if (!is.null(site_results$annual_results) && nrow(site_results$annual_results) > 0) {
        saveRDS(site_results$annual_results, annual_output_file)
      }

      if (scaling_mode && !is.null(partition_id)) {
        period_output_file <- file.path(
          period_output_dir,
          paste0("dc_periodRslt_", actual_sim_id, "_part", partition_id, ".rds")
        )
      } else {
        period_output_file <- file.path(
          period_output_dir,
          paste0("dc_periodRslt_", actual_sim_id, ".rds")
        )
      }
      if (!is.null(site_results$period_results) && nrow(site_results$period_results) > 0) {
        saveRDS(site_results$period_results, period_output_file)
      }

      weighted_mean_output_file <- file.path(weighted_mean_output_dir, paste0("dc_weightedMeanRslt_", actual_sim_id, ".rds"))
      if (!is.null(site_results$weighted_mean_results) &&
          is.data.frame(site_results$weighted_mean_results) &&
          nrow(site_results$weighted_mean_results) > 0) {
        saveRDS(site_results$weighted_mean_results, weighted_mean_output_file)
      }

      end_time <- Sys.time()
      time_stamp <- as.numeric(difftime(end_time, start_time, units = "secs"))

      runtime_info <- data.frame(
        SampleID = actual_sim_id,
        node = node,
        Start = start_time,
        End = end_time,
        Time_sec = time_stamp,
        num_trts = nrow(runFile),
        sim_years = site_results$num_sim_years,
        obs_years = site_results$num_obs_years,
        status = 0,
        message = "Execution Success..",
        stringsAsFactors = FALSE
      )

      runtime_file <- file.path(run_status_dir, paste0("RunTime_SIR_Sim_", actual_sim_id, ".csv"))
      write.csv(runtime_info, runtime_file, row.names = FALSE)

    } else if (sir_db_run_type == "database") {
      db_cfg <- config$file_source$database$database_result
      job_group_label <- group_id
      simulation_id <- actual_sim_id

      end_time <- Sys.time()
      time_stamp <- as.numeric(difftime(end_time, start_time, units = "secs"))

      runtime_info <- data.frame(
        SampleID = actual_sim_id,
        node = node,
        Start = start_time,
        End = end_time,
        Time_sec = time_stamp,
        num_trts = nrow(runFile),
        sim_years = site_results$num_sim_years,
        obs_years = site_results$num_obs_years,
        status = 0,
        message = "Execution Success..",
        stringsAsFactors = FALSE
      )

      tryCatch({
        if (!requireNamespace("DBI", quietly = TRUE)) {
          if (verbose) cat("Warning: DBI package not available; skipping database_result write\n")
          stop("DBI not available")
        }
        has_mariadb <- requireNamespace("RMariaDB", quietly = TRUE)
        has_mysql <- requireNamespace("RMySQL", quietly = TRUE)
        if (!has_mariadb && !has_mysql) {
          if (verbose) cat("Warning: RMariaDB/RMySQL not available; skipping database_result write\n")
          stop("No database driver")
        }

        host <- config$file_source$database$host
        database <- config$file_source$database$database
        cred_file <- config$file_source$database$cred_file %||% "~/.dblogin"

        if (is.null(host) || is.null(database)) {
          stop("database_result host/database not fully specified in config")
        }

        cred_path <- path.expand(cred_file)
        if (!file.exists(cred_path)) {
          stop("Credential file for database_result not found: ", cred_path)
        }
        cred <- readLines(cred_path, warn = FALSE)
        if (length(cred) < 2) {
          stop("Credential file for database_result must contain at least 2 lines (username, password)")
        }
        username <- trimws(cred[1])
        password <- trimws(cred[2])

        con <- if (has_mariadb) {
          DBI::dbConnect(
            RMariaDB::MariaDB(),
            host = host,
            dbname = database,
            username = username,
            password = password
          )
        } else {
          DBI::dbConnect(
            RMySQL::MySQL(),
            host = host,
            dbname = database,
            username = username,
            password = password
          )
        }
        on.exit(DBI::dbDisconnect(con), add = TRUE)

        tbls <- if ("tables" %in% names(db_cfg)) db_cfg$tables else list()

        if (scaling_mode && !is.null(partition_id)) {
          if (!is.null(site_results$annual_results) && nrow(site_results$annual_results) > 0 &&
              "sir_results_annual" %in% names(tbls)) {
            annual_table <- paste0("part", partition_id, "_", tbls$sir_results_annual)
            annual_to_write <- site_results$annual_results
            annual_to_write$job_group <- job_group_label
            annual_to_write$simulation_id <- simulation_id
            annual_to_write$partition_id <- partition_id
            DBI::dbWriteTable(con, annual_table, annual_to_write, append = TRUE, row.names = FALSE)
          }
        } else {
          if (!is.null(site_results$annual_results) && nrow(site_results$annual_results) > 0 &&
              "sir_results_annual" %in% names(tbls)) {
            annual_table <- tbls$sir_results_annual
            annual_to_write <- site_results$annual_results
            annual_to_write$job_group <- job_group_label
            annual_to_write$simulation_id <- simulation_id
            DBI::dbWriteTable(con, annual_table, annual_to_write, append = TRUE, row.names = FALSE)
          }
        }

        if (!is.null(site_results$daily_results) && nrow(site_results$daily_results) > 0 &&
            "sir_results_daily" %in% names(tbls)) {
          daily_table <- tbls$sir_results_daily
          daily_to_write <- site_results$daily_results
          daily_to_write$job_group <- job_group_label
          daily_to_write$simulation_id <- simulation_id
          DBI::dbWriteTable(con, daily_table, daily_to_write, append = TRUE, row.names = FALSE)
        }

        if (!is.null(runtime_info) && nrow(runtime_info) > 0 &&
            "sir_results_run_status" %in% names(tbls)) {
          run_status_table <- tbls$sir_results_run_status
          run_status_to_write <- runtime_info
          run_status_to_write$job_group <- job_group_label
          run_status_to_write$simulation_id <- simulation_id
          run_status_to_write$partition_id <- partition_id
          DBI::dbWriteTable(con, run_status_table, run_status_to_write, append = TRUE, row.names = FALSE)
        }

        if (!is.null(site_results$weighted_mean_results) &&
            is.data.frame(site_results$weighted_mean_results) &&
            nrow(site_results$weighted_mean_results) > 0 &&
            "sir_results_weighted" %in% names(tbls)) {
          w_table <- tbls$sir_results_weighted
          w_to_write <- site_results$weighted_mean_results
          w_to_write$job_group <- job_group_label
          w_to_write$simulation_id <- simulation_id
          DBI::dbWriteTable(con, w_table, w_to_write, append = TRUE, row.names = FALSE)
        }

        DBI::dbDisconnect(con)
      }, error = function(e) {
        if (verbose) {
          cat("Warning: Failed to write SIR Step 2 results to database_result: ",
              conditionMessage(e), "\n")
        }
      })
    } else {
      warning("Unknown database_result$run_type '", sir_db_run_type, "'; expected file_system or database")
    }
    
    # Clean up scratch directory if requested
    if (clean_scratch && dir.exists(sim_dir_tid)) {
      unlink(sim_dir_tid, recursive = TRUE)
    }
    
    complete <- TRUE
    
    # Update output result
    output_result$status <- 0
    output_result$daily_results <- site_results$daily_results
    output_result$annual_results <- site_results$annual_results  # Add annual_results to output
    output_result$aggregated_results <- site_results$aggregated_results
    output_result$weighted_mean_results <- site_results$weighted_mean_results  # Add weighted_mean_results to output
    output_result$runtime_info <- runtime_info
    
    # Only report files that were actually created
    output_files_list <- list()
    
    # Daily output file (conditional)
    if (!is.null(site_results$daily_results) && nrow(site_results$daily_results) > 0) {
      output_files_list$daily_output <- daily_output_file
    }
    
    # Aggregated output file (conditional)
    if (!is.null(site_results$aggregated_results) && nrow(site_results$aggregated_results) > 0 &&
        ncol(site_results$aggregated_results) > 1) {  # Only report if has real variables beyond SampleID
      output_files_list$aggregated_output <- agg_output_file
    }
    
    # Annual output file (conditional)
    if (!is.null(site_results$annual_results) && nrow(site_results$annual_results) > 0) {
      output_files_list$annual_output <- annual_output_file
    }

    # Weighted mean output file (conditional)
    if (!is.null(site_results$weighted_mean_results) &&
        is.data.frame(site_results$weighted_mean_results) &&
        nrow(site_results$weighted_mean_results) > 0) {
      output_files_list$weighted_mean_output <- weighted_mean_output_file
    }

    # Runtime info file (file_system only; database mode writes status to DB)
    if (!is.null(runtime_file)) {
      output_files_list$runtime_info <- runtime_file
    }
    
    output_result$output_files <- output_files_list
    
    if (verbose) cat("--- SIR Step 2 Individual Simulation Successfully Completed ---\n")
    
  }, error = function(err) {
    
    if (verbose) {
      cat("--- SIR Step 2 Individual Simulation Failed ---\n")
      cat("Error:", as.character(err), "\n")
    }
    
    # Calculate error runtime
    end_time <- Sys.time()
    time_stamp <- as.numeric(difftime(end_time, start_time, units = "secs"))
    
    # Create error runtime info matching GSA Step 2 format
    runtime_info <- data.frame(
      SampleID = actual_sim_id,
      node = node,
      Start = start_time,
      End = end_time,
      Time_sec = time_stamp,
      num_trts = ifelse(exists("num_trts"), num_trts, 0),
      sim_years = ifelse(exists("num_sim_years"), num_sim_years, 0),
      obs_years = ifelse(exists("num_obs_years"), num_obs_years, 0),
      status = 1,
      message = as.character(err),
      stringsAsFactors = FALSE
    )
    
    # Try to save error info (file_system) or append run status (database)
    if (exists("run_status_dir") && !is.null(run_status_dir) && dir.exists(run_status_dir)) {
      runtime_file <- file.path(run_status_dir, paste0("RunTime_SIR_Sim_", actual_sim_id, "_error.csv"))
      write.csv(runtime_info, runtime_file, row.names = FALSE)
      output_result$output_files$runtime_info <- runtime_file
    } else {
      db_res <- config$file_source$database$database_result
      if (!is.null(db_res) && !is.null(db_res$run_type) && db_res$run_type == "database" &&
          exists("group_id")) {
        tryCatch({
          if (!requireNamespace("DBI", quietly = TRUE)) {
            stop("DBI not available")
          }
          has_mariadb <- requireNamespace("RMariaDB", quietly = TRUE)
          has_mysql <- requireNamespace("RMySQL", quietly = TRUE)
          if (!has_mariadb && !has_mysql) {
            stop("No database driver")
          }
          host <- config$file_source$database$host
          database <- config$file_source$database$database
          cred_file <- config$file_source$database$cred_file %||% "~/.dblogin"
          if (is.null(host) || is.null(database)) {
            stop("database host/database not specified")
          }
          cred_path <- path.expand(cred_file)
          if (!file.exists(cred_path)) {
            stop("Credential file not found")
          }
          cred <- readLines(cred_path, warn = FALSE)
          username <- trimws(cred[1])
          password <- trimws(cred[2])
          con <- if (has_mariadb) {
            DBI::dbConnect(RMariaDB::MariaDB(), host = host, dbname = database,
                          username = username, password = password)
          } else {
            DBI::dbConnect(RMySQL::MySQL(), host = host, dbname = database,
                          username = username, password = password)
          }
          on.exit(DBI::dbDisconnect(con), add = TRUE)
          tbls <- if ("tables" %in% names(db_res)) db_res$tables else list()
          if ("sir_results_run_status" %in% names(tbls)) {
            status_to_write <- runtime_info
            status_to_write$job_group <- group_id
            status_to_write$simulation_id <- actual_sim_id
            status_to_write$partition_id <- partition_id
            DBI::dbWriteTable(con, tbls$sir_results_run_status, status_to_write,
                             append = TRUE, row.names = FALSE)
          }
          DBI::dbDisconnect(con)
        }, error = function(e) {
          if (verbose) {
            cat("Warning: Failed to write SIR Step 2 error status to database_result: ",
                conditionMessage(e), "\n")
          }
        })
      }
    }
    
    output_result$runtime_info <- runtime_info
    
    # Clean up on error if requested
    if (clean_scratch && exists("sim_dir_tid") && dir.exists(sim_dir_tid)) {
      unlink(sim_dir_tid, recursive = TRUE)
    }
  })
  
  return(output_result)
}

#' SIR Step 2 Simulate
#'
#' SLURM task wrapper for SIR Step 2 simulation. Maps SLURM task ID to
#' simulation ID and calls the individual simulation function.
#'
#' @param config A complete YAML configuration object loaded with read_yaml_config()
#' @param task_id The SLURM task ID for this simulation instance
#' @param daycent_exe Path to DayCent executable file
#' @param scratch_dir Scratch directory for temporary simulation files
#' @param clean_scratch Logical indicating whether to clean scratch files after simulation
#' @param start_id Starting ID offset for task numbering (default: 0)
#' @param shared_connection Optional shared database connection (for connection pooling)
#' @param verbose Logical indicating whether to print progress messages (default: TRUE)
#' @return List containing simulation results
#' @export
sir_step2_simulate <- function(config, task_id, daycent_exe, scratch_dir,
                              clean_scratch = TRUE, start_id = 0, partition_id_override = NULL,
                              shared_connection = NULL, verbose = TRUE) {
  
  # Initialize timing and status tracking
  start_time <- Sys.time()
  node <- Sys.info()[4]
  
  # Adjust task_id with start_id offset
  actual_task_id <- start_id + task_id
  
  if (verbose) {
    cat("====================================================================\n")
    cat("SIR Step 2 - Model Simulation\n")
    cat("Node:", node, "\n")
    cat("Working Directory:", getwd(), "\n\n")
    cat("Configuration:\n")
    cat("\t Project Name                :", config$project$name, "\n")
    cat("\t DayCent Executable          :", daycent_exe, "\n")
    cat("\t Scratch Directory           :", scratch_dir, "\n")
    cat("\t Clean Scratch               :", clean_scratch, "\n")
    cat("\t Actual Task ID              :", actual_task_id, "\n\n")
    cat("====================================================================\n")
  }
  
  # Call individual simulation function
  tryCatch({
    
    result <- sir_step2_simulate_individual(
      config = config,
      sim_id = actual_task_id,
      daycent_exe = daycent_exe,
      scratch_dir = scratch_dir,
      clean_scratch = clean_scratch,
      start_id = 0,  # sim_id already adjusted
      partition_id_override = partition_id_override,  # Pass through for scaling mode
      shared_connection = shared_connection,
      verbose = verbose
    )
    
    # Return the result from individual simulation
    return(result)
    
  }, error = function(err) {
    
    if (verbose) {
      cat("--- SIR Step 2 Simulation Failed ---\n")
      cat("Error:", as.character(err), "\n")
    }
    
    # Calculate error runtime
    end_time <- Sys.time()
    time_stamp <- as.numeric(difftime(end_time, start_time, units = "secs"))
    
    # Create error runtime info matching GSA Step 2 format
    runtime_info <- data.frame(
      SampleID = actual_task_id,
      node = node,
      Start = start_time,
      End = end_time,
      Time_sec = time_stamp,
      num_trts = 0,
      sim_years = 0,
      obs_years = 0,
      status = 1,
      message = as.character(err),
      stringsAsFactors = FALSE
    )
    
    # Return error result
    return(list(
      status = 1,
      daily_results = NULL,
      annual_results = NULL,
      aggregated_results = NULL,
      weighted_mean_results = NULL,
      runtime_info = runtime_info,
      task_id = actual_task_id,
      output_files = list()
    ))
  })
}
