#' Step 2 Scaling Mode Functions
#'
#' This file contains functions for distributing simulation workload across
#' multiple jobs in scaling mode, enabling scalable crop calibration with
#' hundreds of NRI points.
#'
#' @author Generated by Claude Code for DayCent Calibration Framework
#' @note Created October 2025

#' Assign Points to Jobs for Scaling Mode
#'
#' Distributes NRI points (sites) evenly across parallel jobs for Step 2 execution.
#' This enables scalable crop calibration by controlling runtime through point distribution.
#'
#' @param site_ids Character vector of site IDs from RunFile
#' @param points_per_job Integer number of points per job (from config)
#' @param verbose Logical indicating whether to print progress messages
#' @return Data frame with columns:
#'   \item{job_id}{Job identifier (1, 2, 3, ...)}
#'   \item{site_id}{Site identifier assigned to this job}
#'   \item{total_jobs}{Total number of jobs created}
#'   \item{points_in_job}{Number of points in this specific job}
#'
#' @details
#' Distribution strategy:
#' - Sites are assigned sequentially to jobs
#' - Each job gets `points_per_job` sites (except possibly the last job)
#' - Last job gets remaining sites (may be fewer than points_per_job)
#' - Example: 451 sites with points_per_job=50 creates 10 jobs
#'   - Jobs 1-9: 50 points each
#'   - Job 10: 1 point
#'
#' @examples
#' \dontrun{
#' # Distribute 451 NRI points across jobs with 50 points each
#' site_ids <- paste0("site_", 1:451)
#' assignments <- assign_points_to_jobs(site_ids, points_per_job = 50)
#'
#' # Result: 10 jobs (9 with 50 points, 1 with 1 point)
#' table(assignments$job_id)
#' }
#'
#' @export
assign_points_to_jobs <- function(site_ids, points_per_job, verbose = TRUE) {

  # Validate inputs
  if (length(site_ids) == 0) {
    stop("site_ids cannot be empty")
  }

  if (points_per_job < 1) {
    stop("points_per_job must be at least 1")
  }

  # Get unique sites (in case RunFile has multiple treatments per site)
  unique_sites <- unique(site_ids)
  n_sites <- length(unique_sites)

  # Calculate number of jobs needed
  n_jobs <- ceiling(n_sites / points_per_job)

  if (verbose) {
    cat("=== Point Assignment for Scaling Mode ===\n")
    cat("Total unique sites:", n_sites, "\n")
    cat("Points per job:", points_per_job, "\n")
    cat("Total jobs created:", n_jobs, "\n")
  }

  # Assign each site to a job
  job_assignments <- data.frame(
    site_id = unique_sites,
    job_id = rep(1:n_jobs, each = points_per_job, length.out = n_sites),
    stringsAsFactors = FALSE
  )

  # Count points in each job
  points_per_job_actual <- table(job_assignments$job_id)

  # Add metadata columns
  job_assignments$total_jobs <- n_jobs
  job_assignments$points_in_job <- as.integer(points_per_job_actual[as.character(job_assignments$job_id)])

  if (verbose) {
    cat("\nJob distribution:\n")
    for (job_id in 1:n_jobs) {
      n_points <- sum(job_assignments$job_id == job_id)
      cat("  Job", job_id, ":", n_points, "points\n")
    }
    cat("\n")
  }

  return(job_assignments)
}


#' Get Assigned Sites for Current Job
#'
#' Retrieves the list of sites assigned to the current SLURM job based on
#' the point assignment file created in Step 1.
#'
#' @param point_assignments_file Path to point_assignments.rds file
#' @param current_job_id Current SLURM job ID (from SLURM_ARRAY_TASK_ID)
#' @param verbose Logical indicating whether to print progress messages
#' @return Character vector of site IDs assigned to this job
#'
#' @details
#' This function is called by Step 2 to determine which sites to simulate.
#' - In legacy mode: Returns all sites (no filtering)
#' - In scaling mode: Returns subset of sites for this job
#'
#' @examples
#' \dontrun{
#' # Load assignments and get sites for job 5
#' my_sites <- get_assigned_sites_for_job(
#'   "results/crop_yield_corn_m2/10Oct2025/GSA/soboljansen/point_assignments.rds",
#'   current_job_id = 5
#' )
#' }
#'
#' @export
get_assigned_sites_for_job <- function(point_assignments_file, current_job_id, verbose = TRUE) {

  # Check if file exists
  if (!file.exists(point_assignments_file)) {
    stop("Point assignments file not found: ", point_assignments_file)
  }

  # Load assignments
  assignments <- readRDS(point_assignments_file)

  # Filter for current job
  my_sites <- assignments$site_id[assignments$job_id == current_job_id]

  if (length(my_sites) == 0) {
    stop("No sites found for job_id ", current_job_id,
         ". Max job_id in file: ", max(assignments$job_id))
  }

  if (verbose) {
    cat("=== Site Assignment for Job", current_job_id, "===\n")
    cat("Sites assigned to this job:", length(my_sites), "\n")
    cat("Total jobs:", unique(assignments$total_jobs), "\n")
    cat("\n")
  }

  return(my_sites)
}


#' Check if Scaling Mode is Enabled
#'
#' Determines if Step 2 should run in scaling mode based on configuration.
#'
#' @param config Configuration object from read_yaml_config()
#' @return Logical TRUE if scaling mode enabled, FALSE for legacy mode
#'
#' @details
#' Checks for:
#' 1. step2_execution$mode exists and equals "scaling"
#' 2. If missing or "legacy", returns FALSE (default backward compatibility)
#'
#' @examples
#' \dontrun{
#' config <- read_yaml_config("workflows/configs/crop_yield_corn_m2.yaml")
#' if (is_scaling_mode_enabled(config)) {
#'   # Use scaling execution
#' } else {
#'   # Use legacy execution
#' }
#' }
#'
#' @export
is_scaling_mode_enabled <- function(config) {

  # Check if step2_execution exists in config
  if (!"step2_execution" %in% names(config)) {
    return(FALSE)  # Default to legacy mode
  }

  # Check if mode is set to "scaling"
  if (!"mode" %in% names(config$step2_execution)) {
    return(FALSE)  # Default to legacy mode
  }

  # Return TRUE only if explicitly set to "scaling"
  return(config$step2_execution$mode == "scaling")
}


#' Get Points Per Job Configuration
#'
#' Extracts the points_per_job setting from configuration.
#'
#' @param config Configuration object from read_yaml_config()
#' @return Integer number of points per job, or NULL if not in scaling mode
#'
#' @details
#' Returns NULL if:
#' - Not in scaling mode
#' - scaling_config section missing
#' - points_per_job setting missing
#'
#' @examples
#' \dontrun{
#' config <- read_yaml_config("workflows/configs/crop_yield_corn_m2.yaml")
#' points <- get_points_per_job_config(config)
#' if (!is.null(points)) {
#'   cat("Running with", points, "points per job\n")
#' }
#' }
#'
#' @export
get_points_per_job_config <- function(config) {

  # Must be in scaling mode
  if (!is_scaling_mode_enabled(config)) {
    return(NULL)
  }

  # Check for scaling_config section
  if (!"scaling_config" %in% names(config$step2_execution)) {
    warning("Scaling mode enabled but scaling_config section missing")
    return(NULL)
  }

  # Extract points_per_job
  if (!"points_per_job" %in% names(config$step2_execution$scaling_config)) {
    warning("Scaling mode enabled but points_per_job setting missing")
    return(NULL)
  }

  return(as.integer(config$step2_execution$scaling_config$points_per_job))
}
